export const DEFAULT_SUMMARY_FIELDS = {
  age: true,
  callDate: true,
  callerId: true,
  callLastedOver: true,
  callTime: true,
  callerType: true,
  concernCode: true,
  counsellorName: true,
  flow: true,
  formalDiagnosis: true,
  gender: true,
  keyConcerns: true,
  listeningRatio: true,
  location: true,
  moodImprovedBy: true,
  profession: true,
  usedCopilot: true,
  youAsked: true,
};
