import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Gives every opportunity a short, human-quotable code: OPP-0001, OPP-0002, …
 *
 * WHY: the only handle on an opportunity today is a uuid, which nobody reads out in a standup or
 * types into a search box. A short code is what people actually use to refer to one ("let's do
 * OPP-142"), and it is stable in a way the description is not — descriptions get reworded, and
 * split/merge rewrites them outright.
 *
 * ## Generated by a SEQUENCE and a column DEFAULT, not by application code
 *
 * The default is `'OPP-' || lpad(nextval(...))`, so every insert path gets a code for free —
 * the create endpoint, the consumer bug-report path, and both halves of split/merge, which
 * create rows the service layer never sees individually. Doing it in the service would mean
 * finding every writer and would leave a row with no code the moment one is missed.
 *
 * A sequence rather than `max(code) + 1`: that read-then-increment is a race under concurrent
 * inserts, and this codebase has already been bitten by exactly that pattern (see the
 * `nextSequence` note in the Builder work). `nextval` is atomic.
 *
 * Sequence gaps are FINE and expected — a rolled-back insert consumes a value. The code is an
 * identifier, not a count; nothing should ever infer "how many opportunities exist" from it.
 *
 * ## Backfill order
 *
 * Existing rows are numbered by `createdAt` ASC, so the codes read in the order things were
 * actually filed rather than in uuid order. `id` breaks ties so the result is deterministic if
 * two rows share a timestamp (the Supabase import wrote rows in bulk, so ties are likely).
 *
 * Soft-deleted rows are included: they still exist, can still be referenced from a release note
 * or a comment, and skipping them would make the numbering lie about filing order.
 */
export class AddRoadmapOpportunityCode1940600000000 implements MigrationInterface {
  name = 'AddRoadmapOpportunityCode1940600000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE SEQUENCE "roadmap_opportunity_code_seq" AS bigint START WITH 1`,
    );
    await queryRunner.query(
      `ALTER TABLE "roadmap_opportunities" ADD COLUMN "code" character varying(20)`,
    );

    // Backfill in filing order. setval afterwards is not needed: every existing row consumes a
    // value here, so the sequence is already positioned past the highest code.
    await queryRunner.query(`
      UPDATE "roadmap_opportunities" AS o
         SET "code" = 'OPP-' || lpad(ordered.seq::text, 4, '0')
        FROM (
          SELECT "id",
                 nextval('roadmap_opportunity_code_seq') AS seq
            FROM (
              SELECT "id"
                FROM "roadmap_opportunities"
               ORDER BY "createdAt" ASC, "id" ASC
            ) AS in_order
        ) AS ordered
       WHERE o."id" = ordered."id"
    `);

    await queryRunner.query(`
      ALTER TABLE "roadmap_opportunities"
        ALTER COLUMN "code" SET NOT NULL,
        ALTER COLUMN "code" SET DEFAULT ('OPP-' || lpad(nextval('roadmap_opportunity_code_seq')::text, 4, '0'))
    `);
    // UNIQUE across every row including soft-deleted ones: a code that could be reissued after a
    // delete would make an old reference point at a different opportunity.
    await queryRunner.query(`
      ALTER TABLE "roadmap_opportunities"
        ADD CONSTRAINT "UQ_roadmap_opps_code" UNIQUE ("code")
    `);
    // Codes are typed into the search box, so the lookup wants an index of its own.
    await queryRunner.query(
      `CREATE INDEX "idx_roadmap_opps_code" ON "roadmap_opportunities" ("code")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_roadmap_opps_code"`);
    await queryRunner.query(
      `ALTER TABLE "roadmap_opportunities" DROP CONSTRAINT IF EXISTS "UQ_roadmap_opps_code"`,
    );
    await queryRunner.query(
      `ALTER TABLE "roadmap_opportunities" DROP COLUMN IF EXISTS "code"`,
    );
    await queryRunner.query(
      `DROP SEQUENCE IF EXISTS "roadmap_opportunity_code_seq"`,
    );
  }
}
