FROM node:24-alpine

WORKDIR /app

RUN mkdir -p /tmp/audio_storage

RUN mkdir -p /mnt/audio_storage

COPY package*.json ./

# Install build dependencies for native modules (bcrypt)
RUN apk add --no-cache python3 make g++ ffmpeg

# Install dependencies fresh in the container
RUN npm install

COPY . .

RUN npm run build

EXPOSE 8000

CMD ["npm", "run", "start:dev"]
