export enum PromptCode {
  OPENAI_TRANSLATION_SYSTEM_PROMPT_CODE = 'openai_translation_system',
  OPENAI_TRANSLATION_USER_PROMPT_CODE = 'openai_translation_user',
  OPENAI_GUARDRAIL_TRANSLATION_PROMPT_CODE = 'openai_translation_system_guardrail',
  OPENAI_BEHAVIOR_INSTRUCTION_TRANSLATION_PROMPT_CODE = 'openai_translation_learn_behavior_instruction',
  OPENAI_SESSION_EVENT_TRANSLATION_PROMPT_CODE = 'openai_translation_session_event',
  OPENAI_TEXT_TRANSLATION_PROMPT_CODE = 'openai_translation_text',
  OPENAI_SIMULATION_CHARACTER_PROFILE_TEXT_PROMPT_CODE = 'openai_simulation_character_profile_text',
  OPENAI_SIMULATION_CHALLENGE_DESCRIPTION_PROMPT_CODE = 'openai_simulation_challenge_description',
  OPENAI_SIMULATION_STATES_INSTRUCTIONS_PROMPT_CODE = 'openai_simulation_states_instructions',
  OPENAI_SIMULATION_OPENING_DIALOGUES_PROMPT_CODE = 'openai_simulation_opening_dialogues',
  OPENAI_SIMULATION_BEHAVIOR_INSTRUCTIONS_PROMPT_CODE = 'openai_simulation_behavior_instructions',
  OPENAI_SIMULATION_LINGUISTIC_STYLE_SAMPLES_PROMPT_CODE = 'openai_simulation_linguistic_style_samples',
  OPENAI_SIMULATION_LINGUISTIC_STYLE_SAMPLES_ENGLISH_PROMPT_CODE = 'openai_simulation_linguistic_style_samples_english',
  ALLY_AI_LEARN_DEFAULT = 'ally_ai_learn_default',
  ALLY_AI_LEARN_CLIENT_PERSONA_TEMPLATE = 'ally_ai_learn_client_persona_template',
  ALLY_AI_LEARN_PROSODY_GENERATION = 'ally_ai_learn_prosody_generation',
  ALLY_AI_LEARN_PROSODY_UNIFIED = 'ally_ai_learn_prosody_unified',
  ALLY_AI_LEARN_PROSODY_PARAMETERS_ONLY = 'ally_ai_learn_prosody_parameters_only',
}
