import {
  CustomFieldEditPermission,
  CustomFieldFillMode,
  CustomFieldType,
  SingleSelectOption,
} from '../entity/custom-field-definition.entity';

/**
 * Template for seeding one CustomFieldDefinition per tenant from a formerly
 * "built-in" scribe summary field. `seedKey` is the field's original key in
 * `FlattenedSummaryNotePayloadCamelCase` — used only for idempotent
 * re-seeding and matching blob values during the historical backfill; it has
 * no effect on runtime behavior once the row exists.
 */
export interface DefaultFieldTemplate {
  seedKey: string;
  name: string;
  fieldType: CustomFieldType;
  /** Must be one of ally-web's frontend SummarySectionKey values, NOT the
   * backend's own SUMMARY_SECTIONS ids — the two vocabularies don't match,
   * and only the frontend one is what CallSummary.tsx actually renders by. */
  sectionKey: string;
  fillMode: CustomFieldFillMode;
  enhanceable: boolean;
  displayOrder: number;
  options?: SingleSelectOption[];
  /** Passed as this field's key_descriptions entry when fillMode is AI
   * (dynamic per-tenant fill via fillAiCustomFields). Mutually exclusive
   * with `extractFromAiResponseKey`. */
  aiInstruction?: string;
  /**
   * For fillMode: AI fields NOT populated via the dynamic fillAiCustomFields
   * mechanism — instead their value is extracted from the existing
   * fixed-schema `generateSummaryAndTags` AI response (the same call that
   * produces `sessionSummary`/`tags`) at the key named here. Wired up in
   * Phase 2c; this field is just metadata until then. Mutually exclusive
   * with `aiInstruction`.
   */
  extractFromAiResponseKey?: string;
  /** Defaults to BOTH (see seedDefaultDefinitionsForTenant) if omitted. */
  editPermission?: CustomFieldEditPermission;
}

const YES_NO_OPTIONS: SingleSelectOption[] = [
  { id: 'Yes', label: 'Yes', order: 0 },
  { id: 'No', label: 'No', order: 1 },
];

// Every item marked "list, newline-separated" below is one of the fields
// StructuredSummaryNote returns as string[] today (call.details.type.ts:43-49)
// — the dynamic AI-fill mechanism has no per-field type info, so the model
// must be told explicitly to keep multi-point answers as one newline-joined
// string instead of e.g. a comma-separated blob.
const LIST_FORMAT_HINT =
  'If there are multiple points, put each on its own line within a single string — do not return a list or comma-separate them.';

export const DEFAULT_FIELD_TEMPLATES: DefaultFieldTemplate[] = [
  // ─── Features and Demographics ───────────────────────────────────────────
  {
    seedKey: 'newCallFollowUp',
    name: 'New Call Follow Up',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: false,
    displayOrder: 0,
    aiInstruction: 'Indicates if this is a new or follow-up call.',
  },
  {
    seedKey: 'counsellor',
    name: 'Counsellor',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: false,
    displayOrder: 1,
    aiInstruction: 'Name of the counsellor handling the session, if mentioned.',
  },
  {
    seedKey: 'age',
    name: 'Age',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: false,
    displayOrder: 2,
    options: [
      '0-5',
      '6-12',
      '13-17',
      '18-24',
      '25-34',
      '35-44',
      '45-54',
      '55-64',
      '65+',
    ].map((value, order) => ({ id: value, label: value, order })),
    aiInstruction: 'Age range of the client.',
  },
  {
    seedKey: 'gender',
    name: 'Gender',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: false,
    displayOrder: 3,
    options: ['Male', 'Female', 'Non-binary', 'Client Prefers Not to Say'].map(
      (value, order) => ({ id: value, label: value, order }),
    ),
    aiInstruction: 'Gender of the client.',
  },
  {
    seedKey: 'profession',
    name: 'Profession',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: false,
    displayOrder: 4,
    aiInstruction: 'Profession of the client, if mentioned.',
  },
  {
    seedKey: 'relationshipStatus',
    name: 'Relationship status',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: false,
    displayOrder: 5,
    aiInstruction: 'Relationship status of the client, if mentioned.',
  },
  {
    seedKey: 'codeOfConcern',
    name: 'Concern code',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: false,
    displayOrder: 6,
    aiInstruction: 'Code of concern for the session, if applicable.',
  },

  // ─── Narrative / session sections (each its own section today) ──────────
  {
    seedKey: 'counselingProcessFlow',
    name: 'Flow',
    fieldType: CustomFieldType.MULTILINE_TEXT,
    sectionKey: 'flow',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: true,
    displayOrder: 7,
    aiInstruction: `Sequential flow of the counseling session broken down into distinct phases or stages. ${LIST_FORMAT_HINT}`,
  },
  {
    seedKey: 'keyConcerns',
    name: 'Key concerns',
    fieldType: CustomFieldType.MULTILINE_TEXT,
    sectionKey: 'keyConcerns',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: true,
    displayOrder: 8,
    aiInstruction: `Key concerns shared by the client. ${LIST_FORMAT_HINT}`,
  },
  {
    seedKey: 'objectiveObservations',
    name: 'Objective Observations',
    fieldType: CustomFieldType.MULTILINE_TEXT,
    sectionKey: 'objectiveObservations',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: true,
    displayOrder: 9,
    aiInstruction: `Objective observations of the client. ${LIST_FORMAT_HINT}`,
  },
  {
    seedKey: 'subjectiveObservations',
    name: 'Subjective Observations',
    fieldType: CustomFieldType.MULTILINE_TEXT,
    sectionKey: 'subjectiveObservations',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: true,
    displayOrder: 10,
    aiInstruction: `Subjective observations of the client. ${LIST_FORMAT_HINT}`,
  },
  {
    seedKey: 'assessment',
    name: 'Assessment',
    fieldType: CustomFieldType.MULTILINE_TEXT,
    sectionKey: 'assessment',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: true,
    displayOrder: 11,
    aiInstruction: 'Assessment of the client.',
  },
  {
    seedKey: 'dominantFeelings',
    name: 'Dominant Feelings',
    fieldType: CustomFieldType.MULTILINE_TEXT,
    sectionKey: 'dominantFeelings',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: true,
    displayOrder: 12,
    aiInstruction: `Dominant feelings expressed by the client. ${LIST_FORMAT_HINT}`,
  },
  {
    seedKey: 'issuesWorkedOn',
    name: 'Issues Worked On',
    fieldType: CustomFieldType.MULTILINE_TEXT,
    sectionKey: 'issuesWorkedOn',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: true,
    displayOrder: 13,
    aiInstruction: `Issues worked on during the session. ${LIST_FORMAT_HINT}`,
  },
  {
    seedKey: 'keyTherapeuticTechniques',
    name: 'Key Therapeutic Techniques',
    fieldType: CustomFieldType.MULTILINE_TEXT,
    sectionKey: 'keyTherapeuticTechniques',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: true,
    displayOrder: 14,
    aiInstruction: `Key therapeutic techniques used. ${LIST_FORMAT_HINT}`,
  },
  {
    seedKey: 'referralsProvided',
    name: 'Referrals Provided',
    fieldType: CustomFieldType.MULTILINE_TEXT,
    sectionKey: 'referralsProvided',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: true,
    displayOrder: 15,
    aiInstruction: `Referrals provided to the client. ${LIST_FORMAT_HINT}`,
  },
  {
    seedKey: 'homework',
    name: 'Homework Recommended',
    fieldType: CustomFieldType.MULTILINE_TEXT,
    sectionKey: 'homeworkRecommended',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: true,
    displayOrder: 16,
    aiInstruction: `Homework or tasks assigned to the client. ${LIST_FORMAT_HINT}`,
  },
  {
    seedKey: 'planForNextCall',
    name: 'Plans for Next Call',
    fieldType: CustomFieldType.MULTILINE_TEXT,
    sectionKey: 'plansForNextCall',
    fillMode: CustomFieldFillMode.AI,
    enhanceable: true,
    displayOrder: 17,
    aiInstruction: `Plan for the next call. ${LIST_FORMAT_HINT}`,
  },

  // ─── Intake (all manual — never AI-generated today) ──────────────────────
  {
    seedKey: 'intakeNotes',
    name: 'Intake Notes',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 18,
  },
  {
    seedKey: 'riskSelfHarm',
    name: 'Risk, Self Harm',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 19,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'riskSelfHarmNotes',
    name: 'Risk, Self Harm Notes',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 20,
  },
  {
    seedKey: 'riskSuicidalThoughts',
    name: 'Risk, Suicidal Thoughts',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 21,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'riskSuicidalThoughtsNotes',
    name: 'Risk, Suicidal Thoughts Notes',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 22,
  },
  {
    seedKey: 'riskSuicidalPlan',
    name: 'Risk, Suicidal Plan',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 23,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'riskSuicidalAction',
    name: 'Risk, Suicidal Action',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 24,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'riskRunningAway',
    name: 'Risk, Running Away',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 25,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'riskRunningAwayNotes',
    name: 'Risk, Running Away Notes',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 26,
  },
  {
    seedKey: 'traumaPhysicalAbuse',
    name: 'Trauma, Physical Abuse',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 27,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'traumaSexualAbuse',
    name: 'Trauma, Sexual Abuse',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 28,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'traumaVerbalAbuse',
    name: 'Trauma, Verbal Abuse',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 29,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'traumaNeglect',
    name: 'Trauma, Neglect',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 30,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'traumaSeparationFromCaregiverParent',
    name: 'Trauma, Separation from Caregiver/Parent',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 31,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'traumaWitnessedDomesticViolence',
    name: 'Trauma, Witnessed Domestic Violence',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 32,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'traumaNotes',
    name: 'Trauma Notes',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 33,
  },
  {
    seedKey: 'assessmentPsychologicalDiagnosis',
    name: 'Assessment, Psychological Diagnosis',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 34,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'assessmentPsychologicalDiagnosisNotes',
    name: 'Assessment, Psychological Diagnosis Notes',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 35,
  },
  {
    seedKey: 'assessmentUseOfPsychotropicMedications',
    name: 'Assessment, Use of Psychotropic Medications',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 36,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'assessmentUseOfPsychotropicMedicationsNotes',
    name: 'Assessment, Use of Psychotropic Medications Notes',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 37,
  },
  {
    seedKey: 'assessmentHallucinations',
    name: 'Assessment, Hallucinations',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 38,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'assessmentHallucinationsNotes',
    name: 'Assessment, Hallucinations Notes',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 39,
  },
  {
    seedKey: 'assessmentAffect',
    name: 'Assessment, Affect',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 40,
    options: ['Congruent', 'Incongruent', 'Flat', 'Blunted'].map(
      (value, order) => ({ id: value, label: value, order }),
    ),
  },
  {
    seedKey: 'assessmentSpeech',
    name: 'Assessment, Speech',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'intake',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 41,
    options: [
      'Clear & Coherent',
      'Stuttering',
      'Fast',
      'Slow',
      'Difficult to Understand',
    ].map((value, order) => ({ id: value, label: value, order })),
  },

  // ─── Ongoing Risks (all manual — never AI-generated today) ──────────────
  {
    seedKey: 'ongoingRiskSelfHarm',
    name: 'Ongoing Risk, Self Harm',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'ongoingRisks',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 42,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'ongoingRiskSelfHarmNotes',
    name: 'Ongoing Risk, Self Harm Notes',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'ongoingRisks',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 43,
  },
  {
    seedKey: 'ongoingRiskSuicidalThoughts',
    name: 'Ongoing Risk, Suicidal Thoughts',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'ongoingRisks',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 44,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'ongoingRiskSuicidalPlan',
    name: 'Ongoing Risk, Suicidal Plan',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'ongoingRisks',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 45,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'ongoingRiskSuicidalAction',
    name: 'Ongoing Risk, Suicidal Action',
    fieldType: CustomFieldType.SINGLE_SELECT,
    sectionKey: 'ongoingRisks',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 46,
    options: YES_NO_OPTIONS,
  },
  {
    seedKey: 'ongoingRiskSuicidalThoughtsNotes',
    name: 'Ongoing Risk, Suicidal Thoughts Notes',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'ongoingRisks',
    fillMode: CustomFieldFillMode.MANUAL,
    enhanceable: false,
    displayOrder: 47,
  },

  // ─── Extracted from the existing fixed-schema AI response, read-only ────
  // These are already generated today by the same generateSummaryAndTags
  // call that produces sessionSummary/tags (which stay hardcoded) — no new
  // AI call is needed. editPermission: READ_ONLY blocks edits from every
  // role; fillMode: AI alone would not.
  {
    seedKey: 'callType',
    name: 'Call Type',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.AI,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 48,
    extractFromAiResponseKey: 'callType',
  },
  {
    seedKey: 'languages',
    name: 'Languages',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.AI,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 49,
    extractFromAiResponseKey: 'languages',
  },
  {
    seedKey: 'callQuality',
    name: 'Call Quality',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.AI,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 50,
    extractFromAiResponseKey: 'callQuality',
  },
  {
    seedKey: 'reflectiveQuestionsAsked',
    name: 'Reflective Questions Asked',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'metrics',
    fillMode: CustomFieldFillMode.AI,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 51,
    extractFromAiResponseKey: 'reflectiveQuestionsAsked',
  },
  {
    seedKey: 'openEndedQuestionsAsked',
    name: 'Open Ended Questions Asked',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'metrics',
    fillMode: CustomFieldFillMode.AI,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 52,
    extractFromAiResponseKey: 'openEndedQuestionsAsked',
  },
  {
    seedKey: 'emotionalLift',
    name: 'Emotional Lift',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'metrics',
    fillMode: CustomFieldFillMode.AI,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 53,
    extractFromAiResponseKey: 'emotionalLift',
  },

  // ─── System-computed, never persisted ────────────────────────────────────
  // Computed live from Chat/CallDetails/User data by system-field-computer.ts
  // every time getValues() runs — never written to ChatCustomFieldValue.
  // A persisted snapshot would go stale the moment the underlying data
  // changes (e.g. a corrected call duration).
  {
    seedKey: 'callId',
    name: 'Call ID',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.SYSTEM,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 54,
  },
  {
    seedKey: 'callDuration',
    name: 'Call Duration',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.SYSTEM,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 55,
  },
  {
    seedKey: 'callDate',
    name: 'Call Date',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.SYSTEM,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 56,
  },
  {
    seedKey: 'callTime',
    name: 'Call Time',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.SYSTEM,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 57,
  },
  {
    seedKey: 'clientId',
    name: 'Client ID',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.SYSTEM,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 58,
  },
  {
    // Matches ally-web's SummaryFieldKey.CounsellorName enum VALUE
    // ("counselorName", single L, US spelling) — a pre-existing spelling
    // inconsistency in that codebase (every other field there uses British
    // "counsellor"). seedKey must match the frontend value exactly, since
    // the frontend infers per-tenant migration status by matching a
    // hardcoded field's key against seeded custom fields' seedKeys.
    seedKey: 'counselorName',
    name: 'User Name',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.SYSTEM,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 59,
  },
  {
    seedKey: 'mode',
    name: 'Mode',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'featuresAndDemographics',
    fillMode: CustomFieldFillMode.SYSTEM,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 60,
  },
  {
    seedKey: 'listeningShare',
    name: 'Listening Share',
    fieldType: CustomFieldType.TEXT,
    sectionKey: 'metrics',
    fillMode: CustomFieldFillMode.SYSTEM,
    editPermission: CustomFieldEditPermission.READ_ONLY,
    enhanceable: false,
    displayOrder: 61,
  },
];
