export const PERMISSIONS = [
  'VIEW:NAVBAR:CALLS',
  'VIEW:NAVBAR:CALENDAR',
  'VIEW:NAVBAR:ANALYTICS',
  'VIEW:NAVBAR:LEARN',
  'VIEW:NAVBAR:STRESS_BUSTER',
  'VIEW:NAVBAR:SETTINGS',
];

export const GROUPS = [
  'CLIENT',
  'COUNSELOR',
  'ADMIN',
];
