export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
}

export enum UserRole {
  CLIENT = 'CLIENT',
  COUNSELOR = 'COUNSELOR',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum UserPreference {
  SUMMARY_CUSTOMIZED_FIELDS = 'SUMMARY_CUSTOMIZED_FIELDS',
  NUDGE_STATUS = 'NUDGE_STATUS',
}
