/**
 * Admin Analytics Chart Registry — the canonical map from a stable chart id
 * ("admin analytics question id", e.g. `AAQ-042`) to the chart it names.
 *
 * ## What this is
 * Every chart, KPI tile and funnel rendered under the admin console's
 * **Analytics** section (all tabs and Highlights sub-tabs) carries a stable id.
 * The id is assigned once and never changes when a chart is restyled, moved to
 * another tab or renamed — it is the handle used to refer to one specific chart
 * in code review, tickets and requests ("update AAQ-042"). The `tab`/`subTab`
 * fields are mutable metadata that record where the chart lives *today*.
 *
 * ## Why it lives here (and is served read-only)
 * This mirrors the AI Task Registry pattern: a single checked-in source of truth
 * in ally-be, served read-only at `GET /v1/analytics/chart-registry`, so the
 * id -> chart mapping is queryable from one place rather than reconstructable
 * only by reading the frontend. The frontend (ally-web admin dashboard) passes
 * the matching literal id at each chart's call site via the `chartId` prop on
 * `ChartCard` / `KpiTile`, which renders a quiet badge. The two must stay in
 * sync: when you add, remove or renumber a chart, update this file in the same
 * change.
 *
 * ## Conventions
 * - Ids are flat and sequential: `AAQ-001`, `AAQ-002`, … zero-padded to three
 *   digits. Flat (not namespaced by tab) so an id survives a chart moving tabs.
 * - Numbering follows the on-screen order: Highlights first (in sub-tab order),
 *   then the remaining top-level tabs in the order they appear in the tab strip.
 * - A `kind` of `group` marks one id that stands for a set rendered from a
 *   single call site (a KPI strip mapped over an array, or a data-driven chart
 *   whose series are generated at runtime) — the id names the block, not one
 *   series. `dynamic` marks a tab whose chart is generated wholly at runtime.
 * - `unmounted` entries are chart components that exist in the analytics folder
 *   but are not currently rendered by any live tab; they keep a reserved id so
 *   remounting one does not renumber everything after it.
 * - A chart that is deleted outright has its id RETIRED, not reassigned: its
 *   entry is removed and a comment left in its place saying what it was and
 *   why it went (e.g. AAQ-011, AAQ-037..039, AAQ-070).
 */

export type AdminAnalyticsChartKind =
  | 'chart' // a normal Carbon chart in a ChartCard
  | 'kpi' // a KPI stat tile
  | 'funnel' // a FunnelBars funnel (inside a ChartCard)
  | 'group' // one id standing for a mapped/aggregated set at a single call site
  | 'dynamic' // a chart generated entirely at runtime
  | 'unmounted'; // exists in the codebase but not rendered by a live tab today

export interface AdminAnalyticsChartEntry {
  /** Stable id, e.g. `AAQ-042`. Never reused, never renumbered. */
  id: string;
  /** Top-level Analytics tab label as shown in the tab strip. */
  tab: string;
  /** Highlights sub-tab label, when the chart lives under Highlights. */
  subTab?: string;
  /** Human title as rendered above the chart (or the KPI tile's label). */
  title: string;
  /** What kind of element this id names. */
  kind: AdminAnalyticsChartKind;
  /** The Carbon component / body type, e.g. `LineChart`, `StackedBarChart`. */
  chartType?: string;
  /** Path to the component that renders it, relative to the ally-web repo root. */
  componentFile: string;
  /** Anything a reader needs to know: grouping, provenance, caveats. */
  note?: string;
}

const ADMIN_DASHBOARD_ROOT = 'ally-web/apps/ally-admin-dashboard/src/pages';

/** Prefix a path with the admin-dashboard pages root for brevity below. */
const f = (p: string): string => `${ADMIN_DASHBOARD_ROOT}/${p}`;

/**
 * The registry. Ordered by on-screen position. See the file header for the id
 * convention. Populated from the live chart call sites in ally-web.
 */
export const ADMIN_ANALYTICS_CHART_REGISTRY: readonly AdminAnalyticsChartEntry[] =
  [
    // ---- Highlights > Goals ----
    {
      id: 'AAQ-001',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'XP earned vs. goal',
      kind: 'chart',
      chartType: 'GroupedBarChart',
      componentFile: f('Analytics/GoalsXpCard.tsx'),
    },
    {
      id: 'AAQ-002',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Roleplay Minutes',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/RoleplayMinutesCard.tsx'),
    },
    {
      id: 'AAQ-003',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Roleplay Voice Latency',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/RoleplayVoiceLatencyCard.tsx'),
    },
    {
      id: 'AAQ-004',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Roleplay Quality',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/RoleplayQualityCard.tsx'),
    },
    {
      id: 'AAQ-005',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Satisfaction Mix',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/SatisfactionMixCard.tsx'),
    },
    {
      id: 'AAQ-006',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Active Learners (XP)',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/ActiveUsersXpCard.tsx'),
    },
    {
      id: 'AAQ-007',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'New Levels Reached per Period',
      kind: 'chart',
      chartType: 'GroupedBarChart',
      componentFile: f('Analytics/XpLevelReachedCard.tsx'),
    },
    {
      id: 'AAQ-008',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Changed Lines Shipped by Repo',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/ShipVolumeCard.tsx'),
    },
    {
      id: 'AAQ-009',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Bugs Prevention',
      kind: 'chart',
      chartType: 'GroupedBarChart',
      componentFile: f('Analytics/BugHunterVolumeCard.tsx'),
    },
    {
      id: 'AAQ-010',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'XP by Tenant',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/XpByTenantCard.tsx'),
      note: 'Grouping picker: day/week/month/quarter/year, or all time as a single bar',
    },

    // ---- Highlights > Platform ----
    // AAQ-011 is retired (2026-09-25): the Ally Certification hero card counted
    // learners past 5,000 lifetime roleplay minutes as "L1 Ally Certified" — an
    // L1 unrelated to the XP levels. Removed with its endpoint so the only
    // L-levels on Analytics are XP levels. Reserved, never reassigned.
    {
      id: 'AAQ-012',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Platform KPI strip',
      kind: 'group',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
      note: 'One id for the ~8-tile strip mapped from an array',
    },
    {
      id: 'AAQ-013',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Practising learners',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-014',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Activation rate',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-015',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Practising learners per period',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-016',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Session completion rate',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-017',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Growth & activity — error state',
      kind: 'chart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
      note: 'Error-state card shown in place of the growth & activity charts',
    },
    {
      id: 'AAQ-018',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'New users per period',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/NewUsersCard.tsx'),
      note: 'Moved from Highlights > Platform to Goals (shown as "Priority") on 2026-09-25',
    },
    {
      id: 'AAQ-019',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Cumulative users',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/CumulativeUsersCard.tsx'),
      note: 'Moved from Highlights > Platform to Goals (shown as "Priority") on 2026-09-25',
    },
    {
      id: 'AAQ-020',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Active users — new vs returning',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/NewVsReturningUsersCard.tsx'),
      note: 'Moved from Highlights > Platform to Goals (shown as "Priority") on 2026-09-25',
    },
    {
      id: 'AAQ-021',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Users by role',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-022',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Total learners',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-023',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Active learners',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-024',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Completed sessions',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-025',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'New learners per month',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-026',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Average simulation play time',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/PlayTimeCard.tsx'),
      note: 'Moved from Highlights > Platform to Goals (shown as "Priority") on 2026-09-25',
    },
    {
      id: 'AAQ-027',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Completed simulations',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-028',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Cumulative XP awarded',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-029',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Active users — DAU / WAU / MAU',
      kind: 'group',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
      note: 'One id for the per-model (DAU/WAU/MAU) charts, mapped from an array',
    },
    {
      id: 'AAQ-030',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Learner satisfaction',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-031',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Learning track funnel',
      kind: 'funnel',
      chartType: 'FunnelBars',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-032',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Completed simulations by organisation',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-033',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'AI cost per completed simulation',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-034',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Total AI spend',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },

    // ---- Highlights > Usage ----
    {
      id: 'AAQ-035',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'New-learner activation funnel',
      kind: 'funnel',
      chartType: 'FunnelBars',
      componentFile: f('Analytics/ActivationFunnelCard.tsx'),
      note: 'Moved from Highlights > Usage to Goals (shown as "Priority") on 2026-09-25',
    },
    {
      id: 'AAQ-036',
      tab: 'Highlights',
      subTab: 'Usage',
      title: 'Time to first practice',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/UsageLevelsSubTab.tsx'),
    },
    // AAQ-037..AAQ-039 are retired (2026-09-25): the learner usage ladder
    // (L1–L5 by lifetime roleplay minutes) — its per-period attainment, holders
    // and account → L1 → L5 funnel. Removed with `/v1/analytics/usage-ladder` so
    // the only L-levels on Analytics are XP levels. Reserved, never reassigned.
    {
      id: 'AAQ-040',
      tab: 'Highlights',
      subTab: 'Usage',
      title: 'Do they come back?',
      kind: 'funnel',
      chartType: 'FunnelBars',
      componentFile: f('Analytics/tabs/UsageLevelsSubTab.tsx'),
    },
    {
      id: 'AAQ-041',
      tab: 'Highlights',
      subTab: 'Usage',
      title: 'Roleplay sessions of N+ minutes',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/UsageLevelsSubTab.tsx'),
    },

    // ---- Highlights > Skill growth ----
    {
      id: 'AAQ-042',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Learners improving',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
    },
    {
      id: 'AAQ-043',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Classified learners',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
    },
    {
      id: 'AAQ-044',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Median first session',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
    },
    {
      id: 'AAQ-045',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Evaluated sessions',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
    },
    {
      id: 'AAQ-046',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Score by Nth evaluated session',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
    },
    {
      id: 'AAQ-047',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Learners improving, holding steady or declining',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
    },
    {
      id: 'AAQ-048',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Competency map — volume against proficiency',
      kind: 'chart',
      chartType: 'ScatterChart',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
    },
    {
      id: 'AAQ-049',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Learners (per-learner history)',
      kind: 'chart',
      chartType: 'table + LineChart panel',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
    },

    // ---- Highlights > Curriculum ----
    {
      id: 'AAQ-050',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Track drop-off by item format',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/CurriculumSubTab.tsx'),
    },
    {
      id: 'AAQ-051',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Language mix of completed sessions',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/CurriculumSubTab.tsx'),
    },
    {
      id: 'AAQ-052',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Most-practised scenarios',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/CurriculumSubTab.tsx'),
    },
    {
      id: 'AAQ-053',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Least-practised scenarios',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/CurriculumSubTab.tsx'),
    },

    // ---- Highlights > Quality & sentiment ----
    {
      id: 'AAQ-054',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Actor goal score',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-055',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Proxy NPS',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-056',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Do they move together?',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-057',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Median quality score',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-058',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Rated 4–5',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-059',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Roleplay quality',
      kind: 'chart',
      chartType: 'ComboChart',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-060',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Roleplay quality — median and spread',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-061',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Satisfaction mix',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-062',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'What low-rated sessions were tagged with',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },

    // ---- Highlights > Coaching & support ----
    {
      id: 'AAQ-063',
      tab: 'Highlights',
      subTab: 'Coaching & support',
      title: 'Sessions shared for review',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/CoachingSupportSubTab.tsx'),
    },
    {
      id: 'AAQ-064',
      tab: 'Highlights',
      subTab: 'Coaching & support',
      title: 'Time to first comment',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/CoachingSupportSubTab.tsx'),
    },
    {
      id: 'AAQ-065',
      tab: 'Highlights',
      subTab: 'Coaching & support',
      title: 'Organisations using Scribe',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/CoachingSupportSubTab.tsx'),
    },
    {
      id: 'AAQ-066',
      tab: 'Highlights',
      subTab: 'Coaching & support',
      title: 'Scribe sessions',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/CoachingSupportSubTab.tsx'),
    },

    // ---- Highlights > Orgs ----
    {
      id: 'AAQ-067',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Orgs active in the last N days',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    {
      id: 'AAQ-068',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Share of orgs active',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    {
      id: 'AAQ-069',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Orgs on the platform',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    // AAQ-070 is retired (2026-09-25): the org ladder funnel (Org created →
    // L1 → L4 by total org practice minutes). Removed with the ladder half of
    // `/v1/analytics/org-engagement` so the only L-levels on Analytics are XP
    // levels. Reserved, never reassigned.
    {
      id: 'AAQ-071',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Orgs active per month',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    {
      id: 'AAQ-072',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Share of orgs active each month',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    {
      id: 'AAQ-073',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Orgs by avg practice minutes per learner',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    {
      id: 'AAQ-074',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Orgs by avg completed sessions per learner',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },

    // ---- Highlights > Unit economics ----
    {
      id: 'AAQ-075',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'USD per N min of practice',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },
    {
      id: 'AAQ-076',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'Learner-caused AI spend',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },
    {
      id: 'AAQ-077',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'Other AI spend',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },
    {
      id: 'AAQ-078',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'Practice minutes',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },
    {
      id: 'AAQ-079',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'AI cost per N minutes of roleplay',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },
    {
      id: 'AAQ-080',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'Where the spend goes',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },

    // ---- Actor quality metrics ----
    {
      id: 'AAQ-081',
      tab: 'Actor quality metrics',
      title: 'Per-metric quality card',
      kind: 'group',
      chartType: 'LineChart / SimpleBarChart',
      componentFile: f('Analytics/tabs/WeakPerformingMetricsTab.tsx'),
      note: 'One id for the per-series cards rendered at runtime (form varies per series)',
    },
    {
      id: 'AAQ-082',
      tab: 'Actor quality metrics',
      title: 'Actor quality metrics — error state',
      kind: 'chart',
      componentFile: f('Analytics/tabs/WeakPerformingMetricsTab.tsx'),
      note: 'Tab-level error placeholder card',
    },
    {
      id: 'AAQ-083',
      tab: 'Actor quality metrics',
      title: 'Actor quality metrics — loading state',
      kind: 'chart',
      componentFile: f('Analytics/tabs/WeakPerformingMetricsTab.tsx'),
      note: 'Tab-level loading placeholder card',
    },
    {
      id: 'AAQ-084',
      tab: 'Actor quality metrics',
      title: 'Score vs session length',
      kind: 'chart',
      chartType: 'stat (Pearson r)',
      componentFile: f('Analytics/tabs/WeakPerformingMetricsTab.tsx'),
      note: 'Single-stat card, no chart body',
    },

    // ---- Latency & reliability ----
    {
      id: 'AAQ-085',
      tab: 'Latency & reliability',
      title: 'What the learner heard first',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-086',
      tab: 'Latency & reliability',
      title: 'Was the filler any good?',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-087',
      tab: 'Latency & reliability',
      title: 'Did it sound like a soundboard?',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-088',
      tab: 'Latency & reliability',
      title: "Fillers the judge couldn't assess for character",
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-089',
      tab: 'Latency & reliability',
      title: 'Time to first voice, by what spoke',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-090',
      tab: 'Latency & reliability',
      title: 'Time to the real reply — live pipeline',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-091',
      tab: 'Latency & reliability',
      title: 'LLM time-to-first-token — live pipeline',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-092',
      tab: 'Latency & reliability',
      title: 'Prompt cache hit rate — live pipeline',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-093',
      tab: 'Latency & reliability',
      title: 'Voice-to-voice latency — historical (backfilled)',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-094',
      tab: 'Latency & reliability',
      title: 'Average latency by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-095',
      tab: 'Latency & reliability',
      title: 'p95 latency by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-096',
      tab: 'Latency & reliability',
      title: 'STT finalize time by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-097',
      tab: 'Latency & reliability',
      title: 'Simulation start latency by startup phase',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-098',
      tab: 'Latency & reliability',
      title: 'Time to first word — live vs historical total',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-099',
      tab: 'Latency & reliability',
      title: 'Agent-join latency (dispatch → join)',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-100',
      tab: 'Latency & reliability',
      title: 'Agent-join failure, mid-session drop and suspected freeze rate',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-101',
      tab: 'Latency & reliability',
      title: 'Worst simulations — response latency',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LatencyByScenarioPanel.tsx'),
    },
    {
      id: 'AAQ-102',
      tab: 'Latency & reliability',
      title: 'Worst simulations — LLM TTFT',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LatencyByScenarioPanel.tsx'),
    },
    {
      id: 'AAQ-103',
      tab: 'Latency & reliability',
      title: 'Every simulation, worst-first',
      kind: 'chart',
      chartType: 'table',
      componentFile: f('Analytics/tabs/LatencyByScenarioPanel.tsx'),
    },
    {
      id: 'AAQ-104',
      tab: 'Latency & reliability',
      title: 'Session-wise latency by simulation',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencySessionsPanel.tsx'),
    },

    // ---- Drift ----
    {
      id: 'AAQ-105',
      tab: 'Drift',
      title: 'Drift rate over time',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-106',
      tab: 'Drift',
      title: 'Drift rate by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-107',
      tab: 'Drift',
      title: 'Kinds of drift',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-108',
      tab: 'Drift',
      title: 'Root cause',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-109',
      tab: 'Drift',
      title: 'Garble severity',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-110',
      tab: 'Drift',
      title: 'STT error type',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-111',
      tab: 'Drift',
      title: 'Drift rate by {dimension}',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },

    // AAQ-112 is intentionally unused: the Drift tab was allocated 8 ids but
    // renders 7 charts. The id is reserved (never reassigned) so that renumbering
    // does not ripple through every id after it. See the file header.

    // ---- Language ----
    {
      id: 'AAQ-113',
      tab: 'Language',
      title: 'Weighted error rate by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-114',
      tab: 'Language',
      title: 'Round-trip WER by voice',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-115',
      tab: 'Language',
      title: 'Weighted error rate by dimension',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-116',
      tab: 'Language',
      title: 'Weighted error rate per layer, weekly',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-117',
      tab: 'Language',
      title: 'Weighted error rate by {experiment dimension}',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-118',
      tab: 'Language',
      title: 'Top error categories',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-119',
      tab: 'Language',
      title: 'Attribution basis (prompt vs model)',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },

    // ---- Language glossary ----
    {
      id: 'AAQ-120',
      tab: 'Language glossary',
      title: 'Total violations by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/GlossaryAdherenceTab.tsx'),
    },
    {
      id: 'AAQ-121',
      tab: 'Language glossary',
      title: 'Top violated terms',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/GlossaryAdherenceTab.tsx'),
    },

    // ---- Retrieval quality (custom markup, badge next to each section heading) ----
    {
      id: 'AAQ-122',
      tab: 'Retrieval quality',
      title: 'Similarity-floor precision curve',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/tabs/RetrievalQualityTab.tsx'),
    },
    {
      id: 'AAQ-123',
      tab: 'Retrieval quality',
      title: 'Per-consumer retrieval breakdown',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/tabs/RetrievalQualityTab.tsx'),
    },
    {
      id: 'AAQ-124',
      tab: 'Retrieval quality',
      title: 'Retrieval gaps',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/tabs/RetrievalQualityTab.tsx'),
    },

    // ---- AI cost ----
    {
      id: 'AAQ-125',
      tab: 'AI cost',
      title: 'Estimated cost by dimension, stacked by segment',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/TokenConsumption.tsx'),
    },
    {
      id: 'AAQ-126',
      tab: 'AI cost',
      title: 'Bug Hunter vs Builder cost over time',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/CodingAgentCost.tsx'),
    },
    {
      id: 'AAQ-127',
      tab: 'AI cost',
      title: 'Bug Hunter spend by model',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/CodingAgentCost.tsx'),
    },
    {
      id: 'AAQ-128',
      tab: 'AI cost',
      title: 'Builder spend by model',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/CodingAgentCost.tsx'),
    },
    {
      id: 'AAQ-129',
      tab: 'AI cost',
      title: 'Fix session cost — Claude vs Gemini',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/FixSessionEngineCost.tsx'),
    },

    // ---- Bug Agent ----
    {
      id: 'AAQ-130',
      tab: 'Bug Agent',
      title: 'Precision',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },
    {
      id: 'AAQ-131',
      tab: 'Bug Agent',
      title: 'Precision by finder',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },
    {
      id: 'AAQ-132',
      tab: 'Bug Agent',
      title: 'Fix throughput',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },
    {
      id: 'AAQ-133',
      tab: 'Bug Agent',
      title: 'Speed',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },
    {
      id: 'AAQ-134',
      tab: 'Bug Agent',
      title: 'Cost',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },
    {
      id: 'AAQ-135',
      tab: 'Bug Agent',
      title: 'Reliability',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },

    // ---- Scribe ----
    {
      id: 'AAQ-136',
      tab: 'Scribe',
      title: 'Scribe overview — error state',
      kind: 'chart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
      note: 'Error placeholder card',
    },
    {
      id: 'AAQ-137',
      tab: 'Scribe',
      title: 'Scribe overview KPI strip',
      kind: 'group',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
      note: 'One id for the mapped strip (Total sessions, Success rate, Processing, Failed, No audio)',
    },
    {
      id: 'AAQ-138',
      tab: 'Scribe',
      title: 'Scribe sessions over time',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-139',
      tab: 'Scribe',
      title: 'Outcome breakdown',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-140',
      tab: 'Scribe',
      title: 'Capture method — all sessions',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-141',
      tab: 'Scribe',
      title: 'Note mode — all sessions',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-142',
      tab: 'Scribe',
      title: 'Summary-failure — error state',
      kind: 'chart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
      note: 'Error placeholder card',
    },
    {
      id: 'AAQ-143',
      tab: 'Scribe',
      title: 'Scribe failure KPI strip',
      kind: 'group',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
      note: 'One id for the mapped strip (Failure rate, Total failed, Retryable share, Timeout share)',
    },
    {
      id: 'AAQ-144',
      tab: 'Scribe',
      title: 'Summary failure rate over time',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-145',
      tab: 'Scribe',
      title: 'Where sessions stop',
      kind: 'funnel',
      chartType: 'FunnelBars',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-146',
      tab: 'Scribe',
      title: 'Failures by capture method',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-147',
      tab: 'Scribe',
      title: 'Failures by note mode',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-148',
      tab: 'Scribe',
      title: 'STT provider reliability',
      kind: 'chart',
      chartType: 'custom (progress-bar rows)',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-149',
      tab: 'Scribe',
      title: 'Summaries by model',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },

    // ---- Product management ----
    {
      id: 'AAQ-150',
      tab: 'Product management',
      title: 'Votes shipped per month, by owner',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/RoadmapDeliveryCard.tsx'),
    },

    // ---- Analytics Agent (dynamic) ----
    {
      id: 'AAQ-151',
      tab: 'Analytics Agent',
      title: 'Analytics Agent runtime chart',
      kind: 'dynamic',
      chartType: 'runtime (Line/Bar/Stacked/Scatter)',
      componentFile: f('Analytics/tabs/AnalyticsAgentTab.tsx'),
      note: 'Chart generated at runtime from the agent response; type and title vary',
    },

    // ---- Unmounted / legacy chart components (kept for reserved ids) ----
    {
      id: 'AAQ-152',
      tab: '(unmounted)',
      title: 'Learner cohort retention',
      kind: 'unmounted',
      chartType: 'heatmap table / LineChart',
      componentFile: f('Analytics/CohortRetentionCard.tsx'),
      note: 'Not rendered by a live tab today',
    },
    {
      id: 'AAQ-153',
      tab: '(unmounted)',
      title: 'Organisation health',
      kind: 'unmounted',
      chartType: 'table',
      componentFile: f('Analytics/OrgHealthCard.tsx'),
      note: 'Not rendered by a live tab today',
    },
    {
      id: 'AAQ-154',
      tab: '(unmounted)',
      title: 'Usage levels — monthly practice-time mix',
      kind: 'unmounted',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/UsageLevelCard.tsx'),
      note: 'Not rendered by a live tab today',
    },
    {
      id: 'AAQ-155',
      tab: '(unmounted)',
      title: 'Roleplay volume — learners by lifetime roleplays completed',
      kind: 'unmounted',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/RoleplayVolumeCard.tsx'),
      note: 'Not rendered by a live tab today',
    },

    // ---- Added after the initial numbering (ids append; never renumbered) ----
    {
      id: 'AAQ-156',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Average Rating',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/AverageRatingCard.tsx'),
      note: 'Sits beside AAQ-005 (Satisfaction Mix) and reads the same quality-distribution ratings',
    },
    {
      id: 'AAQ-157',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Roleplay Cost per Minute',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/RoleplaySessionCostCard.tsx'),
      note: 'Per-session delivery cost (GET /v1/analytics/roleplay-session-cost), stacked by component. Distinct from the Unit economics cost per 10 minutes, which buckets each call by when it ran rather than by its session',
    },
    // ── Bug Agent: volume beside the rates (GET /v1/bug-hunter/metrics/operations) ──
    // Day-bucketed counts, each paired with where the cohort stands now
    // (accepted / declined / undecided). The page range is mapped to the
    // endpoint's day count; "all" and "12m" become its 365-day maximum.
    {
      id: 'AAQ-158',
      tab: 'Bug Agent',
      title: 'Bugs filed per day',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'Distinct bugs by createdAt day (a re-discovery touches its row), stacked by current outcome',
    },
    {
      id: 'AAQ-159',
      tab: 'Bug Agent',
      title: 'Bugs filed per day, by source',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'Only sources present in the window are plotted; each keeps a fixed colour. Table view carries accepted share per source',
    },
    {
      id: 'AAQ-160',
      tab: 'Bug Agent',
      title: 'How hard they were to spot',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'Derived from proven + source: easy (tool output proved it), hard (agent-inferred, verified), reported (a person filed it)',
    },
    {
      id: 'AAQ-161',
      tab: 'Bug Agent',
      title: 'Who raises bugs',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: "Bug Hunter vs staff vs consumers; reported_bug rows split by the linked roadmap row's source. All three always listed",
    },
    {
      id: 'AAQ-162',
      tab: 'Bug Agent',
      title: 'Tokens spent per day, by trigger',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'By trigger, not by phase: in AI mode one sweep finds and fixes, so a finding-vs-fixing split would be invented',
    },
    {
      id: 'AAQ-163',
      tab: 'Bug Agent',
      title: 'Code shown to the sweeps per day',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'Lines in scope from bug_hunt_runs.metadata.breadth; plot starts on the first recorded day (telemetry shipped 2026-09-23). Takeaway gives tokens per line',
    },
    {
      id: 'AAQ-164',
      tab: 'Bug Agent',
      title: 'Tokens by model',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'From per-model llm_usage rows tagged bug_hunter, joined to runs in the window',
    },
    {
      id: 'AAQ-165',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'XP per Roleplay Minute',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/XpPerMinuteCard.tsx'),
      note: 'All XP (xp_events) ÷ roleplay minutes (user_daily_scores, same as Roleplay Minutes), stacked by XP source over one denominator. Defaults to All time (KPI tile); /v1/analytics/xp-per-minute',
    },
    {
      id: 'AAQ-166',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Foundational Helping Skills by Practice',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/FoundationalSkillsCard.tsx'),
      note: "GET /v1/analytics/foundational-skills. Per 5,000-character cut of each learner's own roleplay speech: average foundational helping skills score (1-4) vs the same learners' first cut, n per point. Scenario-independent rubric in src/foundational-skills",
    },
    {
      id: 'AAQ-167',
      tab: 'Latency & reliability',
      title: 'Heard first, by voice model',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
      note: "Companion to AAQ-085: the same first-audio split per TTS voice model (metadata.ttsModel, 'unknown' when unrecorded) over the whole window, from /v1/analytics/voice-latency byVoiceModel. Generative voices (e.g. elevenlabs/eleven_v3) cannot play spoken masking, so a voice-mix shift shows up here rather than as an unexplained regression",
    },
    {
      id: 'AAQ-168',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Overall score, start → now',
      kind: 'kpi',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: "Panel learners' composite (1-4): mean of their start window vs their now window, and the mean of each learner's own change. /v1/analytics/foundational-skills/progress summary",
    },
    {
      id: 'AAQ-169',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Unhelpful behaviour, start → now',
      kind: 'kpi',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Share of the panel with any skill scored 1 in their start window vs their now window. /v1/analytics/foundational-skills/progress summary',
    },
    {
      id: 'AAQ-170',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Skills moving',
      kind: 'kpi',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Skills whose paired start→now average moved by at least thresholds.skillMoveBand, up and down, of those with enough paired learners. /v1/analytics/foundational-skills/progress summary',
    },
    {
      id: 'AAQ-171',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Learners improving',
      kind: 'kpi',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'All learners with thresholds.trendMinCuts+ cuts, classified on their own first half vs last half of cuts. /v1/analytics/foundational-skills/progress trend',
    },
    {
      id: 'AAQ-172',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Overall and by tier, cut by cut',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Balanced panel: composite plus engage / understand / support tier averages at each of cuts 1..N, same learners at every point. /v1/analytics/foundational-skills/progress byCut',
    },
    {
      id: 'AAQ-173',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Unhelpful behaviour, cut by cut',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Balanced panel: share of cuts with any skill scored 1, at each of cuts 1..N. /v1/analytics/foundational-skills/progress byCut',
    },
    {
      id: 'AAQ-174',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Change per skill, start → now',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: "Paired over the panel and opportunity-aware: per skill, mean of each learner's now-window level minus start-window level. Withheld below minSampleSize paired learners. /v1/analytics/foundational-skills/progress skills",
    },
    {
      id: 'AAQ-175',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Who moved on each skill',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Per skill, panel learners whose own level rose / held / fell by thresholds.skillFlatBand or more. /v1/analytics/foundational-skills/progress skills',
    },
    {
      id: 'AAQ-176',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Every skill, cut by cut',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Heatmap table: average level per skill at each of cuts 1..N over the panel; cells below minSampleSize assessments show only n. /v1/analytics/foundational-skills/progress byCut[].skills',
    },
    {
      id: 'AAQ-177',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Level mix per skill, start vs now',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Share of skill assessments at levels 1-4 in the start and now windows over the panel; a skill stuck at one level shows a ceiling. /v1/analytics/foundational-skills/progress skills[].levelMix',
    },
    {
      id: 'AAQ-178',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'How often practice tests each skill',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Platform-wide share of scored cuts that gave an opportunity for each skill. A rarely-tested skill cannot show progress, whatever learners can do. /v1/analytics/foundational-skills/progress skills[].opportunityPct',
    },
    {
      id: 'AAQ-179',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Behaviours that moved',
      kind: 'chart',
      chartType: 'GroupedBarChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Per rubric behaviour (unhelpful / basic / advanced): share of paired panel learners showing it in the start vs now window, biggest movers first. /v1/analytics/foundational-skills/progress behaviours',
    },
    {
      id: 'AAQ-180',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Unhelpful behaviour, person by person',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Panel learners: stopped / still / started / never showing an unhelpful behaviour, start window vs now window. /v1/analytics/foundational-skills/progress unhelpfulTransitions',
    },
    {
      id: 'AAQ-181',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Learners against their own start',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Every measured learner: improving / holding steady / declining on their own first vs last half of cuts, or too early to say. /v1/analytics/foundational-skills/progress trend',
    },
    {
      id: 'AAQ-182',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Change by amount of practice',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Mean own change (first vs last half of cuts) for learners bucketed by how many cuts they have. /v1/analytics/foundational-skills/progress dose',
    },
    {
      id: 'AAQ-183',
      tab: 'Highlights',
      subTab: 'Skills',
      title: 'Learners',
      kind: 'chart',
      chartType: 'table + LineChart panel',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Panel learners with start, now, change, skills up/down and unhelpful flags; opens a per-learner panel from /v1/analytics/foundational-skills/learners?userId=. /v1/analytics/foundational-skills/progress learners',
    },
  ];

/** Total number of registered charts — handy for the guard test and the UI. */
export const ADMIN_ANALYTICS_CHART_COUNT =
  ADMIN_ANALYTICS_CHART_REGISTRY.length;
