/**
 * Admin Analytics Chart Registry — the canonical map from a stable chart id
 * ("admin analytics question id", e.g. `AAQ-042`) to the chart it names.
 *
 * ## What this is
 * Every chart, KPI tile and funnel rendered under the admin console's
 * **Analytics** section (all tabs and Highlights sub-tabs) carries a stable id.
 * The id is assigned once and never changes when a chart is restyled, moved to
 * another tab or renamed — it is the handle used to refer to one specific chart
 * in code review, tickets and requests ("update AAQ-042"). The `tab`/`subTab`
 * fields are mutable metadata that record where the chart lives *today*.
 *
 * ## Why it lives here (and is served read-only)
 * This mirrors the AI Task Registry pattern: a single checked-in source of truth
 * in ally-be, served read-only at `GET /v1/analytics/chart-registry`, so the
 * id -> chart mapping is queryable from one place rather than reconstructable
 * only by reading the frontend. The frontend (ally-web admin dashboard) passes
 * the matching literal id at each chart's call site via the `chartId` prop on
 * `ChartCard` / `KpiTile`, which renders a quiet badge. The two must stay in
 * sync: when you add, remove or renumber a chart, update this file in the same
 * change.
 *
 * ## Conventions
 * - Ids are flat and sequential: `AAQ-001`, `AAQ-002`, … zero-padded to three
 *   digits. Flat (not namespaced by tab) so an id survives a chart moving tabs.
 * - Numbering follows the on-screen order: Highlights first (in sub-tab order),
 *   then the remaining top-level tabs in the order they appear in the tab strip.
 * - A `kind` of `group` marks one id that stands for a set rendered from a
 *   single call site (a KPI strip mapped over an array, or a data-driven chart
 *   whose series are generated at runtime) — the id names the block, not one
 *   series. `dynamic` marks a tab whose chart is generated wholly at runtime.
 * - `unmounted` entries are chart components that exist in the analytics folder
 *   but are not currently rendered by any live tab; they keep a reserved id so
 *   remounting one does not renumber everything after it.
 * - A chart that is deleted outright has its id RETIRED, not reassigned: its
 *   entry is removed and a comment left in its place saying what it was and
 *   why it went (e.g. AAQ-011, AAQ-037..039, AAQ-070).
 */

export type AdminAnalyticsChartKind =
  | 'chart' // a normal Carbon chart in a ChartCard
  | 'kpi' // a KPI stat tile
  | 'funnel' // a FunnelBars funnel (inside a ChartCard)
  | 'group' // one id standing for a mapped/aggregated set at a single call site
  | 'dynamic' // a chart generated entirely at runtime
  | 'unmounted'; // exists in the codebase but not rendered by a live tab today

export interface AdminAnalyticsChartEntry {
  /** Stable id, e.g. `AAQ-042`. Never reused, never renumbered. */
  id: string;
  /** Top-level Analytics tab label as shown in the tab strip. */
  tab: string;
  /** Highlights sub-tab label, when the chart lives under Highlights. */
  subTab?: string;
  /** Human title as rendered above the chart (or the KPI tile's label). */
  title: string;
  /** What kind of element this id names. */
  kind: AdminAnalyticsChartKind;
  /** The Carbon component / body type, e.g. `LineChart`, `StackedBarChart`. */
  chartType?: string;
  /** Path to the component that renders it, relative to the ally-web repo root. */
  componentFile: string;
  /** Anything a reader needs to know: grouping, provenance, caveats. */
  note?: string;
}

const ADMIN_DASHBOARD_ROOT = 'ally-web/apps/ally-admin-dashboard/src/pages';

/** Prefix a path with the admin-dashboard pages root for brevity below. */
const f = (p: string): string => `${ADMIN_DASHBOARD_ROOT}/${p}`;

/**
 * The registry. Ordered by on-screen position. See the file header for the id
 * convention. Populated from the live chart call sites in ally-web.
 */
export const ADMIN_ANALYTICS_CHART_REGISTRY: readonly AdminAnalyticsChartEntry[] =
  [
    // ---- Highlights > Goals ----
    {
      id: 'AAQ-001',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'XP earned vs. goal',
      kind: 'chart',
      chartType: 'GroupedBarChart',
      componentFile: f('Analytics/GoalsXpCard.tsx'),
    },
    {
      id: 'AAQ-002',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Roleplay Minutes',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/RoleplayMinutesCard.tsx'),
    },
    {
      id: 'AAQ-003',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Roleplay Voice Latency',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/RoleplayVoiceLatencyCard.tsx'),
    },
    {
      id: 'AAQ-004',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Roleplay Quality',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/RoleplayQualityCard.tsx'),
    },
    {
      id: 'AAQ-005',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Satisfaction Mix',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/SatisfactionMixCard.tsx'),
    },
    {
      id: 'AAQ-006',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Active Learners (XP)',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/ActiveUsersXpCard.tsx'),
    },
    {
      id: 'AAQ-007',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'New Levels Reached per Period',
      kind: 'chart',
      chartType: 'GroupedBarChart',
      componentFile: f('Analytics/XpLevelReachedCard.tsx'),
    },
    {
      id: 'AAQ-008',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Changed Lines Shipped by Repo',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/ShipVolumeCard.tsx'),
    },
    {
      id: 'AAQ-009',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Bugs Prevention',
      kind: 'chart',
      chartType: 'GroupedBarChart',
      componentFile: f('Analytics/BugHunterVolumeCard.tsx'),
    },
    {
      id: 'AAQ-010',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'XP by Tenant',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/XpByTenantCard.tsx'),
      note: 'Grouping picker: day/week/month/quarter/year, or all time as a single bar',
    },

    // ---- Highlights > Platform ----
    // AAQ-011 is retired (2026-09-25): the Ally Certification hero card counted
    // learners past 5,000 lifetime roleplay minutes as "L1 Ally Certified" — an
    // L1 unrelated to the XP levels. Removed with its endpoint so the only
    // L-levels on Analytics are XP levels. Reserved, never reassigned.
    {
      id: 'AAQ-012',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Platform KPI strip',
      kind: 'group',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
      note: 'One id for the ~8-tile strip mapped from an array',
    },
    {
      id: 'AAQ-013',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Practising learners',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-014',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Activation rate',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-015',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Practising learners per period',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-016',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Session completion rate',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-017',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Growth & activity — error state',
      kind: 'chart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
      note: 'Error-state card shown in place of the growth & activity charts',
    },
    {
      id: 'AAQ-018',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'New users per period',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/NewUsersCard.tsx'),
      note: 'Moved from Highlights > Platform to Goals (shown as "Priority") on 2026-09-25',
    },
    {
      id: 'AAQ-019',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Cumulative users',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/CumulativeUsersCard.tsx'),
      note: 'Moved from Highlights > Platform to Goals (shown as "Priority") on 2026-09-25',
    },
    {
      id: 'AAQ-020',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Active users — new vs returning',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/NewVsReturningUsersCard.tsx'),
      note: 'Moved from Highlights > Platform to Goals (shown as "Priority") on 2026-09-25',
    },
    {
      id: 'AAQ-021',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Users by role',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-022',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Total learners',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-023',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Active learners',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-024',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Completed sessions',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-025',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'New learners per month',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-026',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Average simulation play time',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/PlayTimeCard.tsx'),
      note: 'Moved from Highlights > Platform to Goals (shown as "Priority") on 2026-09-25',
    },
    {
      id: 'AAQ-027',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Completed simulations',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-028',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Cumulative XP awarded',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-029',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Active users — DAU / WAU / MAU',
      kind: 'group',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
      note: 'One id for the per-model (DAU/WAU/MAU) charts, mapped from an array',
    },
    {
      id: 'AAQ-030',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Learner satisfaction',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-031',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Learning track funnel',
      kind: 'funnel',
      chartType: 'FunnelBars',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-032',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Completed simulations by organisation',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-033',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'AI cost per completed simulation',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },
    {
      id: 'AAQ-034',
      tab: 'Highlights',
      subTab: 'Platform',
      title: 'Total AI spend',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/PlatformSubTab.tsx'),
    },

    // ---- Highlights > Usage ----
    {
      id: 'AAQ-035',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'New-learner activation funnel',
      kind: 'funnel',
      chartType: 'FunnelBars',
      componentFile: f('Analytics/ActivationFunnelCard.tsx'),
      note: 'Moved from Highlights > Usage to Goals (shown as "Priority") on 2026-09-25',
    },
    {
      id: 'AAQ-036',
      tab: 'Highlights',
      subTab: 'Usage',
      title: 'Time to first practice',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/UsageLevelsSubTab.tsx'),
    },
    // AAQ-037..AAQ-039 are retired (2026-09-25): the learner usage ladder
    // (L1–L5 by lifetime roleplay minutes) — its per-period attainment, holders
    // and account → L1 → L5 funnel. Removed with `/v1/analytics/usage-ladder` so
    // the only L-levels on Analytics are XP levels. Reserved, never reassigned.
    {
      id: 'AAQ-040',
      tab: 'Highlights',
      subTab: 'Usage',
      title: 'Do they come back?',
      kind: 'funnel',
      chartType: 'FunnelBars',
      componentFile: f('Analytics/tabs/UsageLevelsSubTab.tsx'),
    },
    {
      id: 'AAQ-041',
      tab: 'Highlights',
      subTab: 'Usage',
      title: 'Roleplay sessions of N+ minutes',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/UsageLevelsSubTab.tsx'),
    },

    // ---- Highlights > Skill growth ----
    {
      id: 'AAQ-042',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Learners improving',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
      note: "Share of classified learners (AAQ-043) whose helping-skills composite (R1: FHS cuts, rubric pinned) rose beyond the noise band from the first half of their scored cuts to the last half — the Helping skills tab's learnerTrend classification. Withheld below 5 classified learners. Before 2026-10 this read the LLM judge's score of the AI actor.",
    },
    {
      id: 'AAQ-043',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Classified learners',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
      note: 'Learners with at least FHS_PROGRESS_THRESHOLDS.trendMinCuts (4) scored cuts and a noise estimate; the rest are reported as insufficient. R1.',
    },
    {
      id: 'AAQ-044',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Median first slice',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
      note: "Median helping-skills composite (1–4) of learners' cut 1 (their first 5,000 characters of roleplay speech). Withheld below MIN_SCORE_SAMPLE_SIZE. Was the actor judge score of the first session before 2026-10.",
    },
    {
      id: 'AAQ-045',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Scored slices',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
      note: 'Scored FHS cuts (rubric FHS_RUBRIC_VERSION, test orgs excluded) behind every number on the sub-tab; wire key summary.evaluatedSessions.',
    },
    {
      id: 'AAQ-046',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Helping-skills score by Nth slice',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
      note: "Median + IQR of the FHS composite (1–4) at each learner's cut index 1–12, all learners vs the experienced panel (6+ scored cuts, survivorship control). Gaps are failed cuts. AI judge not validated against human raters. Before 2026-10 plotted the AI actor's judge score by Nth session — not comparable.",
    },
    {
      id: 'AAQ-047',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Learners improving, holding steady or declining',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
      note: 'learnerTrend over all scored cuts (first half vs last half, band = 1.96 × cutNoiseSd × √(2/w)); same classes as the Helping skills tab (steady → "flat"). Bucketed by the month of each learner\'s 4th scored cut. R1.',
    },
    {
      id: 'AAQ-048',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Competency map — practice volume against learner skill level',
      kind: 'chart',
      chartType: 'ScatterChart',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
      note: 'x: completed sessions per scenario competency tag. y: mean FHS level (1–4) of the rubric skill the tag names (COURSE_IMPACT_COMPETENCY_SKILLS), over single-scenario scored cuts of tagged scenarios where the skill was assessable; null below MIN_SCORE_SAMPLE_SIZE cuts (tooFewCuts) or for tags with no rubric skill (noRubricSkill: Non-Verbal, Linking Emotions…, custom). Single-scenario share travels in cutAttribution. Was median actor judge score before 2026-10.',
    },
    {
      id: 'AAQ-049',
      tab: 'Highlights',
      subTab: 'Skill growth',
      title: 'Learners (per-learner history)',
      kind: 'chart',
      chartType: 'table + LineChart panel',
      componentFile: f('Analytics/tabs/SkillGrowthSubTab.tsx'),
      note: 'One row per learner with a scored cut, own first-half vs last-half change and band (sorted by change, never level); drill-down plots one point per scored cut (composite, skill levels, scenarios) beside the unchanged quiz/annotation series. R1.',
    },

    // ---- Highlights > Curriculum ----
    {
      id: 'AAQ-050',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Track drop-off by item format',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/CurriculumSubTab.tsx'),
    },
    {
      id: 'AAQ-051',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Language mix of completed sessions',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/CurriculumSubTab.tsx'),
    },
    {
      id: 'AAQ-052',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Most-practised scenarios',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/CurriculumSubTab.tsx'),
    },
    {
      id: 'AAQ-053',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Least-practised scenarios',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/CurriculumSubTab.tsx'),
    },

    // ---- Highlights > Quality & sentiment ----
    {
      id: 'AAQ-054',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Actor goal score',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-055',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Proxy NPS',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-056',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Do they move together?',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-057',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Median quality score',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-058',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Rated 4–5',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-059',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Roleplay quality',
      kind: 'chart',
      chartType: 'ComboChart',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-060',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Roleplay quality — median and spread',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-061',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Satisfaction mix',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },
    {
      id: 'AAQ-062',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'What low-rated sessions were tagged with',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/QualitySentimentSubTab.tsx'),
    },

    // ---- Highlights > Coaching & support ----
    {
      id: 'AAQ-063',
      tab: 'Highlights',
      subTab: 'Coaching & support',
      title: 'Sessions shared for review',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/CoachingSupportSubTab.tsx'),
    },
    {
      id: 'AAQ-064',
      tab: 'Highlights',
      subTab: 'Coaching & support',
      title: 'Time to first comment',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/CoachingSupportSubTab.tsx'),
    },
    {
      id: 'AAQ-065',
      tab: 'Highlights',
      subTab: 'Coaching & support',
      title: 'Organisations using Scribe',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/CoachingSupportSubTab.tsx'),
    },
    {
      id: 'AAQ-066',
      tab: 'Highlights',
      subTab: 'Coaching & support',
      title: 'Scribe sessions',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/CoachingSupportSubTab.tsx'),
    },

    // ---- Highlights > Orgs ----
    {
      id: 'AAQ-067',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Orgs active in the last N days',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    {
      id: 'AAQ-068',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Share of orgs active',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    {
      id: 'AAQ-069',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Orgs on the platform',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    // AAQ-070 is retired (2026-09-25): the org ladder funnel (Org created →
    // L1 → L4 by total org practice minutes). Removed with the ladder half of
    // `/v1/analytics/org-engagement` so the only L-levels on Analytics are XP
    // levels. Reserved, never reassigned.
    {
      id: 'AAQ-071',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Orgs active per month',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    {
      id: 'AAQ-072',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Share of orgs active each month',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    {
      id: 'AAQ-073',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Orgs by avg practice minutes per learner',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },
    {
      id: 'AAQ-074',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Orgs by avg completed sessions per learner',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/OrgEngagementSubTab.tsx'),
    },

    // ---- Highlights > Unit economics ----
    {
      id: 'AAQ-075',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'USD per N min of practice',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },
    {
      id: 'AAQ-076',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'Learner-caused AI spend',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },
    {
      id: 'AAQ-077',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'Other AI spend',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },
    {
      id: 'AAQ-078',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'Practice minutes',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },
    {
      id: 'AAQ-079',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'AI cost per N minutes of roleplay',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },
    {
      id: 'AAQ-080',
      tab: 'Highlights',
      subTab: 'Unit economics',
      title: 'Where the spend goes',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/UnitEconomicsSubTab.tsx'),
    },

    // ---- Actor quality metrics ----
    {
      id: 'AAQ-081',
      tab: 'Actor quality metrics',
      title: 'Per-metric quality card',
      kind: 'group',
      chartType: 'LineChart / SimpleBarChart',
      componentFile: f('Analytics/tabs/WeakPerformingMetricsTab.tsx'),
      note: 'One id for the per-series cards rendered at runtime (form varies per series)',
    },
    {
      id: 'AAQ-082',
      tab: 'Actor quality metrics',
      title: 'Actor quality metrics — error state',
      kind: 'chart',
      componentFile: f('Analytics/tabs/WeakPerformingMetricsTab.tsx'),
      note: 'Tab-level error placeholder card',
    },
    {
      id: 'AAQ-083',
      tab: 'Actor quality metrics',
      title: 'Actor quality metrics — loading state',
      kind: 'chart',
      componentFile: f('Analytics/tabs/WeakPerformingMetricsTab.tsx'),
      note: 'Tab-level loading placeholder card',
    },
    {
      id: 'AAQ-084',
      tab: 'Actor quality metrics',
      title: 'Score vs session length',
      kind: 'chart',
      chartType: 'stat (Pearson r)',
      componentFile: f('Analytics/tabs/WeakPerformingMetricsTab.tsx'),
      note: 'Single-stat card, no chart body',
    },

    // ---- Latency & reliability ----
    {
      id: 'AAQ-085',
      tab: 'Latency & reliability',
      title: 'What the learner heard first',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-086',
      tab: 'Latency & reliability',
      title: 'Was the filler any good?',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-087',
      tab: 'Latency & reliability',
      title: 'Did it sound like a soundboard?',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-088',
      tab: 'Latency & reliability',
      title: "Fillers the judge couldn't assess for character",
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-089',
      tab: 'Latency & reliability',
      title: 'Time to first voice, by what spoke',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-090',
      tab: 'Latency & reliability',
      title: 'Time to the real reply — live pipeline',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-091',
      tab: 'Latency & reliability',
      title: 'LLM time-to-first-token — live pipeline',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-092',
      tab: 'Latency & reliability',
      title: 'Prompt cache hit rate — live pipeline',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-093',
      tab: 'Latency & reliability',
      title: 'Voice-to-voice latency — historical (backfilled)',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-094',
      tab: 'Latency & reliability',
      title: 'Average latency by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-095',
      tab: 'Latency & reliability',
      title: 'p95 latency by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-096',
      tab: 'Latency & reliability',
      title: 'STT finalize time by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-097',
      tab: 'Latency & reliability',
      title: 'Simulation start latency by startup phase',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-098',
      tab: 'Latency & reliability',
      title: 'Time to first word — live vs historical total',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-099',
      tab: 'Latency & reliability',
      title: 'Agent-join latency (dispatch → join)',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-100',
      tab: 'Latency & reliability',
      title: 'Agent-join failure, mid-session drop and suspected freeze rate',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
    },
    {
      id: 'AAQ-101',
      tab: 'Latency & reliability',
      title: 'Worst simulations — response latency',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LatencyByScenarioPanel.tsx'),
    },
    {
      id: 'AAQ-102',
      tab: 'Latency & reliability',
      title: 'Worst simulations — LLM TTFT',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LatencyByScenarioPanel.tsx'),
    },
    {
      id: 'AAQ-103',
      tab: 'Latency & reliability',
      title: 'Every simulation, worst-first',
      kind: 'chart',
      chartType: 'table',
      componentFile: f('Analytics/tabs/LatencyByScenarioPanel.tsx'),
    },
    {
      id: 'AAQ-104',
      tab: 'Latency & reliability',
      title: 'Session-wise latency by simulation',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LatencySessionsPanel.tsx'),
    },

    // ---- Drift ----
    {
      id: 'AAQ-105',
      tab: 'Drift',
      title: 'Drift rate over time',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-106',
      tab: 'Drift',
      title: 'Drift rate by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-107',
      tab: 'Drift',
      title: 'Kinds of drift',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-108',
      tab: 'Drift',
      title: 'Root cause',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-109',
      tab: 'Drift',
      title: 'Garble severity',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-110',
      tab: 'Drift',
      title: 'STT error type',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },
    {
      id: 'AAQ-111',
      tab: 'Drift',
      title: 'Drift rate by {dimension}',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('ConversationDrift/ConversationDrift.tsx'),
    },

    // AAQ-112 is intentionally unused: the Drift tab was allocated 8 ids but
    // renders 7 charts. The id is reserved (never reassigned) so that renumbering
    // does not ripple through every id after it. See the file header.

    // ---- Language ----
    {
      id: 'AAQ-113',
      tab: 'Language',
      title: 'Weighted error rate by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-114',
      tab: 'Language',
      title: 'Round-trip WER by voice',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-115',
      tab: 'Language',
      title: 'Weighted error rate by dimension',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-116',
      tab: 'Language',
      title: 'Weighted error rate per layer, weekly',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-117',
      tab: 'Language',
      title: 'Weighted error rate by {experiment dimension}',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-118',
      tab: 'Language',
      title: 'Top error categories',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },
    {
      id: 'AAQ-119',
      tab: 'Language',
      title: 'Attribution basis (prompt vs model)',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/LanguageQualityTab.tsx'),
    },

    // ---- Language glossary ----
    {
      id: 'AAQ-120',
      tab: 'Language glossary',
      title: 'Total violations by language',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/GlossaryAdherenceTab.tsx'),
    },
    {
      id: 'AAQ-121',
      tab: 'Language glossary',
      title: 'Top violated terms',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/GlossaryAdherenceTab.tsx'),
    },

    // ---- Retrieval quality (custom markup, badge next to each section heading) ----
    {
      id: 'AAQ-122',
      tab: 'Retrieval quality',
      title: 'Similarity-floor precision curve',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/tabs/RetrievalQualityTab.tsx'),
    },
    {
      id: 'AAQ-123',
      tab: 'Retrieval quality',
      title: 'Per-consumer retrieval breakdown',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/tabs/RetrievalQualityTab.tsx'),
    },
    {
      id: 'AAQ-124',
      tab: 'Retrieval quality',
      title: 'Retrieval gaps',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/tabs/RetrievalQualityTab.tsx'),
    },

    // ---- AI cost ----
    {
      id: 'AAQ-125',
      tab: 'AI cost',
      title: 'Estimated cost by dimension, stacked by segment',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/TokenConsumption.tsx'),
    },
    {
      id: 'AAQ-126',
      tab: 'AI cost',
      title: 'Bug Hunter vs Builder cost over time',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/CodingAgentCost.tsx'),
    },
    {
      id: 'AAQ-127',
      tab: 'AI cost',
      title: 'Bug Hunter spend by model',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/CodingAgentCost.tsx'),
    },
    {
      id: 'AAQ-128',
      tab: 'AI cost',
      title: 'Builder spend by model',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/CodingAgentCost.tsx'),
    },
    {
      id: 'AAQ-129',
      tab: 'AI cost',
      title: 'Fix session cost — Claude vs Gemini',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/FixSessionEngineCost.tsx'),
    },

    // ---- Bug Agent ----
    {
      id: 'AAQ-130',
      tab: 'Bug Agent',
      title: 'Precision',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },
    {
      id: 'AAQ-131',
      tab: 'Bug Agent',
      title: 'Precision by finder',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },
    {
      id: 'AAQ-132',
      tab: 'Bug Agent',
      title: 'Fix throughput',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },
    {
      id: 'AAQ-133',
      tab: 'Bug Agent',
      title: 'Speed',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },
    {
      id: 'AAQ-134',
      tab: 'Bug Agent',
      title: 'Cost',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },
    {
      id: 'AAQ-135',
      tab: 'Bug Agent',
      title: 'Reliability',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
    },

    // ---- Scribe ----
    {
      id: 'AAQ-136',
      tab: 'Scribe',
      title: 'Scribe overview — error state',
      kind: 'chart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
      note: 'Error placeholder card',
    },
    {
      id: 'AAQ-137',
      tab: 'Scribe',
      title: 'Scribe overview KPI strip',
      kind: 'group',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
      note: 'One id for the mapped strip (Total sessions, Success rate, Processing, Failed, No audio)',
    },
    {
      id: 'AAQ-138',
      tab: 'Scribe',
      title: 'Scribe sessions over time',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-139',
      tab: 'Scribe',
      title: 'Outcome breakdown',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-140',
      tab: 'Scribe',
      title: 'Capture method — all sessions',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-141',
      tab: 'Scribe',
      title: 'Note mode — all sessions',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-142',
      tab: 'Scribe',
      title: 'Summary-failure — error state',
      kind: 'chart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
      note: 'Error placeholder card',
    },
    {
      id: 'AAQ-143',
      tab: 'Scribe',
      title: 'Scribe failure KPI strip',
      kind: 'group',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
      note: 'One id for the mapped strip (Failure rate, Total failed, Retryable share, Timeout share)',
    },
    {
      id: 'AAQ-144',
      tab: 'Scribe',
      title: 'Summary failure rate over time',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-145',
      tab: 'Scribe',
      title: 'Where sessions stop',
      kind: 'funnel',
      chartType: 'FunnelBars',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-146',
      tab: 'Scribe',
      title: 'Failures by capture method',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-147',
      tab: 'Scribe',
      title: 'Failures by note mode',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-148',
      tab: 'Scribe',
      title: 'STT provider reliability',
      kind: 'chart',
      chartType: 'custom (progress-bar rows)',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },
    {
      id: 'AAQ-149',
      tab: 'Scribe',
      title: 'Summaries by model',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/tabs/ScribeTab.tsx'),
    },

    // ---- Product management ----
    {
      id: 'AAQ-150',
      tab: 'Product management',
      title: 'Votes shipped per month, by owner',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/RoadmapDeliveryCard.tsx'),
    },

    // ---- Analytics Agent (dynamic) ----
    {
      id: 'AAQ-151',
      tab: 'Analytics Agent',
      title: 'Analytics Agent runtime chart',
      kind: 'dynamic',
      chartType: 'runtime (Line/Bar/Stacked/Scatter)',
      componentFile: f('Analytics/tabs/AnalyticsAgentTab.tsx'),
      note: 'Chart generated at runtime from the agent response; type and title vary',
    },

    // ---- Unmounted / legacy chart components (kept for reserved ids) ----
    {
      id: 'AAQ-152',
      tab: '(unmounted)',
      title: 'Learner cohort retention',
      kind: 'unmounted',
      chartType: 'heatmap table / LineChart',
      componentFile: f('Analytics/CohortRetentionCard.tsx'),
      note: 'Not rendered by a live tab today',
    },
    {
      id: 'AAQ-153',
      tab: '(unmounted)',
      title: 'Organisation health',
      kind: 'unmounted',
      chartType: 'table',
      componentFile: f('Analytics/OrgHealthCard.tsx'),
      note: 'Not rendered by a live tab today',
    },
    {
      id: 'AAQ-154',
      tab: '(unmounted)',
      title: 'Usage levels — monthly practice-time mix',
      kind: 'unmounted',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/UsageLevelCard.tsx'),
      note: 'Not rendered by a live tab today',
    },
    {
      id: 'AAQ-155',
      tab: '(unmounted)',
      title: 'Roleplay volume — learners by lifetime roleplays completed',
      kind: 'unmounted',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/RoleplayVolumeCard.tsx'),
      note: 'Not rendered by a live tab today',
    },

    // ---- Added after the initial numbering (ids append; never renumbered) ----
    {
      id: 'AAQ-156',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Average Rating',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/AverageRatingCard.tsx'),
      note: 'Sits beside AAQ-005 (Satisfaction Mix) and reads the same quality-distribution ratings',
    },
    {
      id: 'AAQ-157',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Roleplay Cost per Minute',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/RoleplaySessionCostCard.tsx'),
      note: 'Per-session delivery cost (GET /v1/analytics/roleplay-session-cost), stacked by component. Distinct from the Unit economics cost per 10 minutes, which buckets each call by when it ran rather than by its session',
    },
    // ── Bug Agent: volume beside the rates (GET /v1/bug-hunter/metrics/operations) ──
    // Day-bucketed counts, each paired with where the cohort stands now
    // (accepted / declined / undecided). The page range is mapped to the
    // endpoint's day count; "all" and "12m" become its 365-day maximum.
    {
      id: 'AAQ-158',
      tab: 'Bug Agent',
      title: 'Bugs filed per day',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'Distinct bugs by createdAt day (a re-discovery touches its row), stacked by current outcome',
    },
    {
      id: 'AAQ-159',
      tab: 'Bug Agent',
      title: 'Bugs filed per day, by source',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'Only sources present in the window are plotted; each keeps a fixed colour. Table view carries accepted share per source',
    },
    {
      id: 'AAQ-160',
      tab: 'Bug Agent',
      title: 'How hard they were to spot',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'Derived from proven + source: easy (tool output proved it), hard (agent-inferred, verified), reported (a person filed it)',
    },
    {
      id: 'AAQ-161',
      tab: 'Bug Agent',
      title: 'Who raises bugs',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: "Bug Hunter vs staff vs consumers; reported_bug rows split by the linked roadmap row's source. All three always listed",
    },
    {
      id: 'AAQ-162',
      tab: 'Bug Agent',
      title: 'Tokens spent per day, by trigger',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'By trigger, not by phase: in AI mode one sweep finds and fixes, so a finding-vs-fixing split would be invented',
    },
    {
      id: 'AAQ-163',
      tab: 'Bug Agent',
      title: 'Code shown to the sweeps per day',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'Lines in scope from bug_hunt_runs.metadata.breadth; plot starts on the first recorded day (telemetry shipped 2026-09-23). Takeaway gives tokens per line',
    },
    {
      id: 'AAQ-164',
      tab: 'Bug Agent',
      title: 'Tokens by model',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'From per-model llm_usage rows tagged bug_hunter, joined to runs in the window',
    },
    {
      id: 'AAQ-165',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'XP per Roleplay Minute',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/XpPerMinuteCard.tsx'),
      note: 'All XP (xp_events) ÷ roleplay minutes (user_daily_scores, same as Roleplay Minutes), stacked by XP source over one denominator. Defaults to All time (KPI tile); /v1/analytics/xp-per-minute',
    },
    {
      id: 'AAQ-166',
      tab: 'Highlights',
      subTab: 'Goals',
      title: 'Foundational Helping Skills by Practice',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/FoundationalSkillsCard.tsx'),
      note: "GET /v1/analytics/foundational-skills?baselineCut=1|2. Per 5,000-character cut of each learner's own roleplay speech: average foundational helping skills score (1-4) vs the same learners' baseline cut (cut 1, or cut 2 to treat cut 1 as a warm-up), with a 95% CI on the paired change, n per point. Scenario-independent rubric in src/foundational-skills",
    },
    {
      id: 'AAQ-167',
      tab: 'Latency & reliability',
      title: 'Heard first, by voice model',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/LatencyTab.tsx'),
      note: "Companion to AAQ-085: the same first-audio split per TTS voice model (metadata.ttsModel, 'unknown' when unrecorded) over the whole window, from /v1/analytics/voice-latency byVoiceModel. Generative voices (e.g. elevenlabs/eleven_v3) cannot play spoken masking, so a voice-mix shift shows up here rather than as an unexplained regression",
    },
    {
      id: 'AAQ-168',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Overall score, start → now',
      kind: 'kpi',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: "Panel composite start→now with the paired bootstrap 95% CI and sign test; says 'no detectable change' unless the CI excludes zero. /v1/analytics/foundational-skills/progress summary.composite",
    },
    {
      id: 'AAQ-169',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Unhelpful behaviour, start → now',
      kind: 'kpi',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Share of the panel with any unhelpful behaviour, start vs now, with a CI in points and stopped/started/still/never counts (absorbed retired AAQ-180). /v1/analytics/foundational-skills/progress summary.unhelpful',
    },
    // AAQ-170 is retired (2026-10-03): "Skills moving: N up · N down" counted skills
    // past a ±0.1 band narrower than a skill's own 95% CI (~±0.2 at n=24), so it
    // headlined noise. Replaced by detectable-only counts on AAQ-174. Reserved.
    {
      id: 'AAQ-170',
      tab: 'Bug Agent',
      title: 'Spend over time',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/BugHunterOperationsCards.tsx'),
      note: 'Estimated cost per period by trigger (metadata.cliReportedCostUsd else totalTokenCostUsd), from GET metrics/operations days; Day / Week / Month folded client-side',
    },
    {
      id: 'AAQ-171',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Learners beyond noise',
      kind: 'kpi',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'All learners with 4+ cuts, own first half vs last half, against a noise-sized band (1.96 · slice noise · √(2/w)) instead of a fixed ±0.15 that labelled ~10/24 as movers by chance. /v1/analytics/foundational-skills/progress trend + precision',
    },
    {
      id: 'AAQ-172',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Overall score, cut by cut',
      kind: 'chart',
      chartType: 'AreaChart (bounded)',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Balanced panel composite at each of cuts 1..N with a 95% bootstrap band (Carbon bounded area); cut 1 marked as warm-up; tier start→now changes with CIs listed under it. /v1/analytics/foundational-skills/progress byCut + tiers',
    },
    {
      id: 'AAQ-173',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Unhelpful behaviour, cut by cut',
      kind: 'chart',
      chartType: 'AreaChart (bounded)',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Share of panel cuts with any unhelpful behaviour at each of cuts 1..N, with a 95% bootstrap band. /v1/analytics/foundational-skills/progress byCut',
    },
    {
      id: 'AAQ-174',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Change per skill, start → now',
      kind: 'chart',
      chartType: 'custom (dot and whisker)',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: "Per skill: paired start→now change ± 95% CI; coloured only when the CI excludes zero; capped and rarely tested skills grouped as 'not measurable'. /v1/analytics/foundational-skills/progress skills",
    },
    // AAQ-175 is retired (2026-10-03): "Who moved on each skill" counted noisy
    // per-learner changes at ±0.5; shuffling each learner's own cuts reproduced the
    // same spread, so it showed chance. Reserved, never reassigned.
    {
      id: 'AAQ-176',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Every skill, cut by cut',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Heatmap table, expanded-view diagnostic: average level per skill at each of cuts 1..N over the panel; capped/rare rows flagged; cells below minSampleSize show only n. /v1/analytics/foundational-skills/progress byCut[].skills',
    },
    {
      id: 'AAQ-177',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Level mix per skill, start vs now',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Share of skill assessments at levels 1-4 in the start and now windows over the panel; a skill stuck at one level shows a ceiling. /v1/analytics/foundational-skills/progress skills[].levelMix',
    },
    {
      id: 'AAQ-178',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Learners with a chance at each skill',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Per skill: learners with 2+ chances, exactly 1, and none — the count the content team can act on (e.g. self-harm, confidentiality). /v1/analytics/foundational-skills/progress skills[].learnersWithOpportunity/TwoPlus',
    },
    {
      id: 'AAQ-179',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Behaviours that moved',
      kind: 'chart',
      chartType: 'custom (change rows)',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Behaviour moves start→now shown only when credible after Benjamini–Hochberg correction across all behaviours (q ≤ 0.05); otherwise says none cleared it. /v1/analytics/foundational-skills/progress behaviours',
    },
    // AAQ-180 is retired (2026-10-03): the unhelpful-transitions donut drew 24 people
    // as an achievement at p=0.42. Its counts now ride in AAQ-169's description.
    // Reserved, never reassigned.
    {
      id: 'AAQ-181',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Learners against their own start',
      kind: 'chart',
      chartType: 'DonutChart',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Every measured learner: improving / holding steady / declining against a noise-sized band on own first vs last half of cuts, or too early (<4 cuts). /v1/analytics/foundational-skills/progress trend',
    },
    // AAQ-182 is retired (2026-10-03): "Change by amount of practice" withheld 3 of 4
    // buckets (below 20 learners) and practice volume is confounded with org and
    // pace. Revisit at ~3x the learners. Reserved, never reassigned.
    {
      id: 'AAQ-183',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Learners',
      kind: 'chart',
      chartType: 'table + LineChart panel',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Panel learners: start, now, change shown against their noise band, and coaching flags (any safety code; other unhelpful codes repeated in 2+ cuts) in words; opens the per-learner panel with scenarios per cut. /v1/analytics/foundational-skills/progress learners',
    },
    {
      id: 'AAQ-184',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Behaviour profile',
      kind: 'chart',
      chartType: 'custom (rows)',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Per rubric behaviour: share of ALL learners showing it in their first cut and ever (where the skill was assessable). Stable, readable, and shows movement inside capped skills. /v1/analytics/foundational-skills/progress behaviours[].firstSlicePct/everPct',
    },
    {
      id: 'AAQ-185',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Self-harm cues: followed up or missed',
      kind: 'chart',
      chartType: 'custom (counts)',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Platform-wide, unaudited judge coding: cue cuts followed up / missed / unclear, first cue per learner, and first vs last for learners with 2+ cues. Internal: share only privately with partners. /v1/analytics/foundational-skills/progress safety.selfHarm',
    },
    {
      id: 'AAQ-186',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Confidentiality: explained, limits, promises',
      kind: 'chart',
      chartType: 'custom (counts)',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Learners who explained confidentiality, listed its limits, explained why, or promised it without exceptions (unaudited). /v1/analytics/foundational-skills/progress safety.confidentiality',
    },
    {
      id: 'AAQ-187',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'How precise is this measure?',
      kind: 'group',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: "Slice noise SD, ICC, minimum detectable change for the panel, a learner's noise band, level/code consistency, and human-rater agreement (not yet measured). /v1/analytics/foundational-skills/progress precision",
    },
    {
      id: 'AAQ-188',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Practice depth',
      kind: 'funnel',
      chartType: 'FunnelBars',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Learners reaching 1, 2, 3, 5 and 10 scored cuts: who is even measurable. /v1/analytics/foundational-skills/progress depth',
    },
    {
      id: 'AAQ-189',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Benchmark scenario, before and after',
      kind: 'chart',
      chartType: 'custom (paired slope)',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'One slope per learner from their FIRST to their LATEST scored session of the SAME benchmark roleplay (scenarios.metadata.fhsBenchmark), counted only when the latest came at least 3 more 5,000-character cuts of practice after the first; a learner with several benchmark scenarios counts once, on the one with the most practice between. Paired mean change with a bootstrap CI and sign test, per-skill where assessable in both; averages null below minSampleSize. /v1/analytics/foundational-skills/benchmark',
    },
    {
      id: 'AAQ-190',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Habits adopted and dropped',
      kind: 'chart',
      chartType: 'custom (change rows)',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: "Per rubric behaviour: learners' own first half vs last half of slices (rate where the skill could be shown), group change ± bootstrap 95% CI, credible only after Benjamini–Hochberg across all behaviours; ICC shown so untrackable behaviours read as such. /v1/analytics/foundational-skills/behaviours behaviours",
    },
    {
      id: 'AAQ-191',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Habit grid',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: "Learners × the most person-specific helpful habits (ICC ≥ 0.1): each learner's rate, with ▲/▼ only where their own start vs now clears Fisher p ≤ 0.05. Self vs self; no ranking. /v1/analytics/foundational-skills/behaviours learners + gridCodes",
    },
    {
      id: 'AAQ-192',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: "A learner's habits, start vs now",
      kind: 'chart',
      chartType: 'custom (rows)',
      componentFile: f('Analytics/tabs/FoundationalSkillsSubTab.tsx'),
      note: 'Learner panel section: every behaviour the learner had a chance at, start vs now counts with a clear adopted/dropped call (Fisher). /v1/analytics/foundational-skills/behaviours?userId=',
    },
    // ---- Highlights > Course impact ----
    {
      id: 'AAQ-193',
      tab: 'Highlights',
      subTab: 'Course impact',
      title: 'Course impact at a glance',
      kind: 'group',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/CourseImpactSubTab.tsx'),
      note: 'Courses with enough paired learners to read (minSampleSize), and of those how many improved, declined (95% interval clear of zero) or are unclear. /v1/analytics/course-impact summary',
    },
    {
      id: 'AAQ-194',
      tab: 'Highlights',
      subTab: 'Course impact',
      title: 'Helping skills before and after, by course',
      kind: 'chart',
      chartType: 'custom (paired rows)',
      componentFile: f('Analytics/tabs/CourseImpactSubTab.tsx'),
      note: "One row per course: its finished learners' helping-skills composite (1–4) from their last 3 slices before starting vs their first 3 made wholly after finishing, each learner against themselves; change ± bootstrap 95% CI, averages null below minSampleSize. A pooled row counts each learner once (earliest-finished course). Grey reference whisker beside every course: learners with no enrolment, read at the course learners' median slice position (k) and gap (g). Associated with, not caused by, the course. /v1/analytics/course-impact courses, pooled, reference",
    },
    {
      id: 'AAQ-195',
      tab: 'Highlights',
      subTab: 'Course impact',
      title: 'Who this course can measure',
      kind: 'funnel',
      chartType: 'FunnelBars',
      componentFile: f('Analytics/tabs/CourseImpactSubTab.tsx'),
      note: 'Selected course: enrolled → started → finished → had practice before → practised after (paired). Says why a course has too few learners to read. /v1/analytics/course-impact courses[].coverage',
    },
    {
      id: 'AAQ-196',
      tab: 'Highlights',
      subTab: 'Course impact',
      title: 'Skill by skill, before and after',
      kind: 'chart',
      chartType: 'custom (paired rows)',
      componentFile: f('Analytics/tabs/CourseImpactSubTab.tsx'),
      note: "Selected course: each rubric skill's level before vs after over learners for whom it was assessable on both sides; skills the course's roleplays assess (competencies mapped to rubric keys) listed first and marked. /v1/analytics/course-impact?trackId= course.skills",
    },
    {
      id: 'AAQ-197',
      tab: 'Highlights',
      subTab: 'Course impact',
      title: 'Unhelpful behaviour, before and after',
      kind: 'chart',
      chartType: 'custom (counts)',
      componentFile: f('Analytics/tabs/CourseImpactSubTab.tsx'),
      note: "Selected course: share of each learner's slices showing any unhelpful or potentially harmful behaviour, before vs after; down is better. /v1/analytics/course-impact?trackId= course.unhelpful",
    },

    // ---- Bug Agent: the panels that moved off the Bug Hunter page's
    // Performance tab (OPP-0749, 2026-10-05); AAQ-167..169 were already taken ----
    {
      id: 'AAQ-198',
      tab: 'Bug Agent',
      title: "How I'm doing (scorecard)",
      kind: 'unmounted',
      chartType: 'kpi',
      componentFile: f('BugHunter/AgentScorecard.tsx'),
      note: 'Four tiles plus fourteen-day sparkbars from GET /v1/bug-hunter/runs. Moved to Analytics → Bug Agent with OPP-0749 and removed from it the same day (2026-10-05, product head): the trends and operations charts already carry these figures',
    },
    {
      id: 'AAQ-199',
      tab: 'Bug Agent',
      title: "How often I'm right (accuracy panel)",
      kind: 'unmounted',
      chartType: 'FunnelBars',
      componentFile: f('BugHunter/AccuracyPanel.tsx'),
      note: 'GET /v1/bug-hunter/metrics: funnel, accuracy by source and decision reason, stage latency, cost per landed fix. Removed from Analytics → Bug Agent on 2026-10-05 with the scorecard; the Precision trend covers the headline rate',
    },
    {
      id: 'AAQ-200',
      tab: 'Bug Agent',
      title: 'My shift log (run history)',
      kind: 'group',
      chartType: 'table',
      componentFile: f('BugHunter/RunHistoryTable.tsx'),
      note: 'Per-run ledger: status, trigger, counts, cost and GitHub run, with the event timeline per row; the only view of a run, so it stays reachable here',
    },
    {
      id: 'AAQ-201',
      tab: 'Bug Agent',
      title: 'Bugs found per day',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/BugAgentPerformance.tsx'),
      note: 'Distinct top-level findings filed per UTC day across every repo and source, excluding any since dismissed or rejected, with a trailing 7-day mean; the one daily series on the tab, there to show the count falling. /v1/analytics/bug-agent-performance found[]',
    },
    // ---- Effectiveness analytics (plan 2026-10-04, docs/effectiveness-analytics-plan.md).
    // Ids follow on-screen order WITHIN this batch: Highlights > Effectiveness, then
    // Helping skills, Usage and Curriculum additions; Phase 2–4 continue at AAQ-217. ----
    {
      id: 'AAQ-202',
      tab: 'Highlights',
      subTab: 'Effectiveness',
      title: 'The chain, link by link',
      kind: 'group',
      chartType: 'kpi',
      componentFile: f('Analytics/tabs/EffectivenessSubTab.tsx'),
      note: "Eight KpiTiles, one per link of the theory of change, each loading from the endpoint that owns the definition and naming that sub-tab: activated learners (activation, all time), measurable learners (2+ scored slices, foundational-skills/progress depth), helping skills start → now (AAQ-168), learners beyond noise (AAQ-171), unhelpful behaviour start → now (AAQ-169), course lift (course-impact pooled, each learner once), self-harm cues followed up (AAQ-185, internal), practice to Engage competence (time-to-competence, median slices). A summary of other tabs' definitions, not new ones.",
    },
    {
      id: 'AAQ-203',
      tab: 'Highlights',
      subTab: 'Effectiveness',
      title: 'Where learners fall out of the chain',
      kind: 'funnel',
      chartType: 'FunnelBars',
      componentFile: f('Analytics/tabs/EffectivenessSubTab.tsx'),
      note: "All-time distinct learners, non-test orgs: signed up (learner-role accounts, the activation population) → completed a countable session → completed two → first scored cut → measurable (2+ cuts) → classifiable (4+) → improving beyond own noise. Stages 1–3 on accounts and sessions, 4–7 on ruler R1 (FHS cuts, pinned rubric); each stage intersected with every stage above (clamp counts who that drops). 'Improving' is AAQ-181's classification, its shares withheld below 20 classifiable learners, steady/declining beside it; a learner with <4 cuts cannot be classified. /v1/analytics/effectiveness/funnel",
    },
    {
      id: 'AAQ-204',
      tab: 'Highlights',
      subTab: 'Effectiveness',
      title: 'Effectiveness by segment',
      kind: 'chart',
      chartType: 'ChangeWhiskers',
      componentFile: f('Analytics/tabs/EffectivenessSubTab.tsx'),
      note: "Ruler R1: the Helping skills panel's paired start→now composite change (overall row = AAQ-168) split by one dimension — majority session language, worker type (current admin label), org size (measured learners 1–9/10–49/50+), course started before 'now' vs free practice, or majority scenario difficulty — each ± bootstrap 95% CI, coloured only when it excludes zero; segments under 20 learners listed as withheld with their n. Segments overlap, so a gap between two is a hypothesis, not a finding. /v1/analytics/foundational-skills/progress/segments?dimension=",
    },
    {
      id: 'AAQ-205',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Time to competence',
      kind: 'chart',
      chartType: 'LineChart (step)',
      componentFile: f('Analytics/FoundationalSkillsTimeSection.tsx'),
      note: "Ruler R1. One step line per tier: Kaplan–Meier share of learners who, by their Nth 5,000-character slice, have reached level 3 (every basic behaviour) at least once on all but one of the tier's MOVABLE skills (Engage 2 of 3, Understand 3 of 4, Support 2 of 3; rapport and family are capped at 2 by the rubric and confidentiality and harm rarely assessable, so they are left out — counting them made Engage unreachable for every learner on 2026-10-05 production data). Learners who stop are censored, not counted as never; at-risk count under each point. One-time crossing, not sustained. KPI: median slices (or 'not reached by half') and median practice minutes among those who reached it; names the skill not-yet-reached learners most often lack. Shares null below minSampleSize at risk; axis ends at minCohortSize. All time. /v1/analytics/foundational-skills/time-to-competence",
    },
    {
      id: 'AAQ-206',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Skill retention after a break',
      kind: 'chart',
      chartType: 'custom (whiskers)',
      componentFile: f('Analytics/FoundationalSkillsTimeSection.tsx'),
      note: "Ruler R1. Consecutive scored slices k → k+1 banded by the gap between them (<7 / 7–13 / 14–29 / 30+ days; gap = first new session's start − slice k's last session end). Per band: composite change averaged per learner, then paired bootstrap 95% CI over learners; <7 days is the no-break reference. Withheld below 20 pairs from 10 learners; counts travel. Associated with a break, not caused by it (self-selected). All time. /v1/analytics/foundational-skills/retention",
    },
    {
      id: 'AAQ-207',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Difficulty mix by practice ordinal',
      kind: 'chart',
      chartType: 'StackedBarChart (100%)',
      componentFile: f('Analytics/FoundationalSkillsTimeSection.tsx'),
      note: "Learner's 1st..12th countable session by scenario difficulty label (EASY / MEDIUM / HARD / untagged), with a fixed 12+-session panel as the survivorship control; counts in the table view. Shares null below minSampleSize sessions. Difficulty is an authoring label (defaults to MEDIUM), not a measured property. All time. /v1/analytics/practice-progression",
    },
    {
      id: 'AAQ-208',
      tab: 'Highlights',
      subTab: 'Usage',
      title: 'Learner talk share per session',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/PracticeQualitySection.tsx'),
      note: 'Ruler R7 (transcript shape). Per countable session: learner characters ÷ all characters (client filler/interim lines dropped), median with p25–p75 band per bucket by session end, plus a median learner-turns line; null below minSampleSize sessions. Compare within one language (characters per word differ by script). /v1/analytics/practice-quality points[].talkShare*, learnerTurnsMedian',
    },
    {
      id: 'AAQ-209',
      tab: 'Highlights',
      subTab: 'Usage',
      title: 'Sessions that count as practice',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/PracticeQualitySection.tsx'),
      note: 'Ruler R7. Share of countable sessions with ≥ 3 learner turns, ≥ 2 minutes net of pauses and ≥ 300 learner characters (practiceThresholds), per bucket; companion to AAQ-041 (minutes only). Takeaway: share with < 3 learner turns. Null below minSampleSize sessions. /v1/analytics/practice-quality points[].practicePct, summary',
    },
    {
      id: 'AAQ-210',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Course funnel',
      kind: 'chart',
      chartType: 'SimpleBarChart (hBarOpts) + table',
      componentFile: f('Analytics/CourseOutcomesSection.tsx'),
      note: 'Ruler R10. Per course, of enrolments created in the window (default 12m): enrolled → started (opened an item) → halfway (≥ 50% items, the tenant course-usage definition) → finished, plus stalled (started, no activity in 30 days) and median/IQR days to finish. Rates null below minCohortSize; top 15 by enrolments drawn (inChart), rest in the table. /v1/analytics/curriculum/course-funnel',
    },
    {
      id: 'AAQ-211',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Pass on first attempt, by quiz',
      kind: 'chart',
      chartType: 'SimpleBarChart (hBarOpts)',
      componentFile: f('Analytics/CourseOutcomesSection.tsx'),
      note: 'Ruler R5. Share of learners whose first attempt (earliest attemptNumber 1, submitted in the window) passed, per quiz, hardest first; null below minSampleSize first attempts. Expanded view: questions most often wrong first time, by id and type only. Open-ended answers are LLM-graded (track-quiz-grading), so a step may be a grader change. /v1/analytics/curriculum/quiz-outcomes quizzes[].passedFirstPct',
    },
    {
      id: 'AAQ-212',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'First → best attempt gain',
      kind: 'chart',
      chartType: 'custom (ChangeWhiskers)',
      componentFile: f('Analytics/CourseOutcomesSection.tsx'),
      note: 'Ruler R5. Per quiz, first vs best scorePct over learners with 2+ scored attempts (one pair per learner), paired bootstrap 95% CI, plus share needing a 2nd attempt. Best ≥ first by construction: it measures what a retry recovers, not learning. Null below minSampleSize. /v1/analytics/curriculum/quiz-outcomes quizzes[].firstToBest',
    },
    {
      id: 'AAQ-213',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Roleplay gates inside courses',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/CourseOutcomesSection.tsx'),
      note: 'Ruler R2 + R10, all time. Per course roleplay with a minScore above 0: progress rows with a linked session, stacked passed first time / passed later / stuck (14 days) / in progress; median attempts to pass; flagged tooHard (< 40% first-time) or tooEasy (> 95%). Session score is scenario-scaled: says whether the gate fits the scenario, not learner skill. Null below minSampleSize. /v1/analytics/curriculum/roleplay-gates',
    },
    {
      id: 'AAQ-214',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Which skills each scenario exercises',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/ScenarioContentSection.tsx'),
      note: 'Ruler R1. Heatmap: scenarios with ≥ minSampleSize single-scenario helping-skills cuts × the 14 rubric skills; cell = share of those cuts where the judge found an opportunity for the skill (skillLevels key present, as AAQ-178). Tagged skills (competency tags → rubric keys) outlined; singleScenarioShare on the card. All time. /v1/analytics/scenarios/opportunity-coverage scenarios',
    },
    {
      id: 'AAQ-215',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Scenario tags that rarely get an opportunity',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/ScenarioContentSection.tsx'),
      note: 'Fix list derived from AAQ-214: (scenario, tagged skill) with opportunity share < 30% over ≥ 20 single-scenario cuts, most sessions played first. Opportunity is the judge’s call; a self-harm cue exists only if the persona produces one. /v1/analytics/scenarios/opportunity-coverage tagGaps',
    },
    {
      id: 'AAQ-216',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Same-scenario repeat improvement',
      kind: 'chart',
      chartType: 'custom (paired slope)',
      componentFile: f('Analytics/ScenarioContentSection.tsx'),
      note: 'Ruler R2 within one scenario version. Per learner × scenario version: first vs latest countable session score, 2+ plays ≥ 1 day apart, unresolved zeros (score 0 with no detected event) dropped. One slope per learner on the selected scenario (picker: top 10 by pairs); per-version paired change ± bootstrap CI in the table; pooled share improving counts each learner once (scale-free). A version does not pin scoring (mappings/behaviour instructions are edited in place): each row carries pairsSpanningScoringChange against the last scoring edit; the score also counts behaviour-instruction points. Floor 20 pairs. /v1/analytics/scenarios/repeat-improvement',
    },
    {
      id: 'AAQ-217',
      tab: 'Highlights',
      subTab: 'Effectiveness',
      title: 'Dose–response: change against practice amount',
      kind: 'chart',
      chartType: 'ScatterChart + fitted line',
      componentFile: f('Analytics/tabs/EffectivenessSubTab.tsx'),
      note: "Ruler R1. One point per learner the Helping skills trend can classify (4+ scored cuts, AAQ-171): x = scored cuts (or minutes of countable practice in those cuts), y = own last-half minus first-half composite change. Least-squares line; slope 95% CI by bootstrapping learners (seeded). Gated: scatter and fits only from 40 classified learners (doseResponse.minLearners), otherwise 'not yet measurable, n = X of 40'. No banding (AAQ-182 was retired for withheld bands). Observational: practice is self-selected and improvers may keep going. Ids only. All time. /v1/analytics/foundational-skills/progress learnersScatter + doseResponse",
    },
    {
      id: 'AAQ-218',
      tab: 'Highlights',
      subTab: 'Effectiveness',
      title: 'Cost per improved learner',
      kind: 'kpi',
      componentFile: f('Analytics/tabs/EffectivenessSubTab.tsx'),
      note: 'Learner-caused AI spend in the window (the AAQ-076 total, same window) ÷ learners classified improving beyond noise (R1, Helping skills classification) whose last scored cut closed in the window. Withheld below 20 improved learners; both sides shown. Ceiling, not a unit price: spend is attributable to all learners, improvement only to the measurable subset. Platform-wide. /v1/analytics/effectiveness/cost-per-improvement',
    },
    {
      id: 'AAQ-219',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Change start → now, within difficulty',
      kind: 'chart',
      chartType: 'ChangeWhiskers',
      componentFile: f('Analytics/FoundationalSkillsTimeSection.tsx'),
      note: "Ruler R1: AAQ-168's paired start→now composite change split by each panel learner's majority scenario difficulty in their start window → their now window (e.g. EASY→HARD; mixed/untagged otherwise), ± bootstrap 95% CI. Renders only when at least one cell clears 20 learners, otherwise the gated empty state. Difficulty is the scenario's current tag and MEDIUM is the column default. /v1/analytics/foundational-skills/progress/segments?dimension=difficultyTransition",
    },
    {
      id: 'AAQ-220',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Transfer to a new scenario',
      kind: 'chart',
      chartType: 'custom (paired slope)',
      componentFile: f('Analytics/FoundationalSkillsValiditySection.tsx'),
      note: 'Ruler R1, single-scenario cuts only (share on the card). For learners with 3+ scored single-scenario cuts: the first cut on a scenario met in no earlier cut (single or mixed, scored or not) against the single-scenario cut just before it, when that one was on a scenario already played. Pairs averaged per learner; paired bootstrap 95% CI + sign test; withheld below 20 learners, slope rows too. A same-difficulty comparison and the harder/same/easier tally ride along: new scenarios are often harder (read with AAQ-207), so a drop can be difficulty or novelty, not lost skill. Associated with, not caused by. All time. /v1/analytics/foundational-skills/transfer',
    },
    {
      id: 'AAQ-221',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Named improvements that were acted on',
      kind: 'chart',
      chartType: 'custom (change rows)',
      componentFile: f('Analytics/FoundationalSkillsValiditySection.tsx'),
      note: "Ruler R1 (L4 feedback loop). Per rubric skill: when a session debrief's areas of growth were filed under the skill (AI task feedback-improvement-skill-mapping, off unless FEEDBACK_SKILL_MAPPING_SCHEDULE=on), did the learner's level rise / hold / fall from their last cut closed by the session's end to their first cut wholly after it — vs the same learners' skills the debrief did not name. One share per learner per skill per role; named − unnamed 'rose' share within learner ± bootstrap 95% CI and sign test; null below minSampleSize. Observational; regression to the mean inflates the named arm. /v1/analytics/foundational-skills/feedback-uptake",
    },
    {
      id: 'AAQ-222',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Do the rulers agree?',
      kind: 'chart',
      chartType: 'table (correlation matrix)',
      componentFile: f('Analytics/FoundationalSkillsValiditySection.tsx'),
      note: 'Rulers R1–R4, R6 (L0 validity). Single-scenario scored cuts, all time: Spearman r with n between R1 FHS composite, R2 session score z within scenario version, R3 behaviour-instruction hit balance, R4 mean skillCoverage, R6 learner rating. Cells below 50 pairs show n only; cut-level (one learner gives several cuts). R2 includes behaviour-instruction points, so R2–R3 agreement is partly mechanical. Agreement is not validity; human ratings are AAQ-223. /v1/analytics/measurement/convergence',
    },
    {
      id: 'AAQ-223',
      tab: 'Highlights',
      subTab: 'Helping skills',
      title: 'Judge vs human agreement',
      kind: 'chart',
      chartType: 'custom-table',
      componentFile: f('Analytics/FoundationalSkillsValiditySection.tsx'),
      note: "Ruler R1 validity (L0). Per rubric skill: Cohen's κ on opportunity and, where both found one, κ (unweighted and quadratic-weighted) and % exact on the 1–4 level, judge vs each human rating and human vs human (all rater pairs on a cut); plus the any-unhelpful flag. Humans tick behaviour codes on a 30-cut-per-quarter sample stratified by composite tercile × session language; levels derived with the judge's rule. κ null below 20 rated cuts, counts travel; 'not yet measured' until ratings exist (no rating UI yet — POST /v1/foundational-skills/human-ratings). One rubric version, test orgs excluded, all time. /v1/analytics/foundational-skills/judge-agreement",
    },
    {
      id: 'AAQ-224',
      tab: 'Highlights',
      subTab: 'Usage',
      title: 'Practice spacing',
      kind: 'chart',
      chartType: 'SimpleBarChart',
      componentFile: f('Analytics/PracticeSpacingCard.tsx'),
      note: "Whole days between a learner's consecutive countable sessions (start to start), all-time, banded 0–1 / 2–6 / 7–13 / 14–29 / 30+ as a share of gaps (null below 20 gaps; 0–1 is massed practice, back-to-back sessions included). KPI: share of active learners (2+ sessions) whose median gap is 7 days or less, one vote each, null below 5. Same learners as the stickiness funnel (LEARNER role, org by the learner's tenant); test orgs excluded. Describes rhythm; does not show spacing helps. /v1/analytics/practice-stickiness spacing",
    },
    {
      id: 'AAQ-225',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Where in a course momentum dies',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/CourseOutcomesSection.tsx'),
      note: "Ruler R10. One line per course (top 5 by started enrolments, ≥ 20 each): x = item position 0–100% of the course's live items in unlock order, y = share of started enrolments that reached it (furthest unlocked item; finished = all). Reached means unlocked, not opened. Expanded view: steepest drop. All time. /v1/analytics/curriculum/progress-curve",
    },
    {
      id: 'AAQ-226',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Does knowing predict doing?',
      kind: 'chart',
      chartType: 'ScatterChart',
      componentFile: f('Analytics/CourseOutcomesSection.tsx'),
      note: 'Rulers R5 × R1. One point per learner × course: mean first-attempt quiz score (x) vs mean helping-skills composite of the first 6 slices after enrolling (y, pinned rubric). Spearman r with a learner-clustered bootstrap CI, withheld below 30 points; per-course r where a course alone has 30. Both measures are noisy; a weak r is expected. /v1/analytics/curriculum/knowledge-vs-skill',
    },
    {
      id: 'AAQ-227',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Scenario difficulty calibration',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/ScenarioContentSection.tsx'),
      note: 'Ruler R2. Per scenario VERSION with ≥ minSampleSize countable scored sessions (unresolved zeros dropped), all time: share of sessions in bands of the attainable score range (Σ positive event score × maxOccurrences + 10 per SHOULD_DO behaviour instruction, an uncapped contributor counted once), read over sessions since the scoring config last changed; raw bands (< 0, 0–49, 50–99, 100+) when no range applies. Authored difficultyLevel alongside; tooEasy (> 80% top band) / tooHard (> 50% below 0) flagged; > 100% counted, never hidden. Measures how scores land, a property of the scoring and the learners. /v1/analytics/scenarios/calibration rows',
    },
    {
      id: 'AAQ-228',
      tab: 'Highlights',
      subTab: 'Curriculum',
      title: 'Did the learner move the client?',
      kind: 'chart',
      chartType: 'StackedBarChart',
      componentFile: f('Analytics/ScenarioContentSection.tsx'),
      note: 'Ruler R9. Per countable session, bucketed by session end: reached the terminal simulation state / advanced past the opening state / never got past it, from the per-turn state on scenario_session_turn_metrics.metadata (from 2026-06-10). Sessions with no usable state (older builds, branching mode, single-state scenarios) counted as untracked under the chart, not plotted; shares null below minSampleSize. States are score-windowed, so this is a learner-progress proxy only as far as event scores track good helping. Expanded view: by scenario. /v1/analytics/scenarios/progression points',
    },
    {
      id: 'AAQ-229',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Satisfaction by practice ordinal',
      kind: 'chart',
      chartType: 'LineChart',
      componentFile: f('Analytics/PerceptionSection.tsx'),
      note: "Ruler R6. The 1–5 post-session rating (latest per session) by the learner's Nth RATED session, ordered by session start, N = 1..12: mean rating and share rated 4–5, all-comers plus a fixed panel of learners with 6+ ratings (survivorship control). Null below 20 ratings per ordinal; counts travel; tail past 12 counted. All time whatever the page window; test orgs and org filter by the session's tenant; preview/seed rooms out. /v1/analytics/quality-distribution byOrdinal",
    },
    {
      id: 'AAQ-230',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Confidence start → now, per tier',
      kind: 'chart',
      chartType: 'custom (ChangeWhiskers)',
      componentFile: f('Analytics/PerceptionSection.tsx'),
      note: "L9 perception. Each learner's self-rated confidence (0–10, self-efficacy instrument v1) on their first vs latest answer, over the items rated both times, per tier (skills in the expanded view); always beside the judge's level change (1–4) at the cuts nearest those answers for the same learners (selfMatched vs judge). Paired change ± bootstrap 95% CI, null below minSampleSize. Never an outcome alone. No learner-facing prompt yet (API: GET/POST /v1/self-assessment), so 'not yet measured' until one ships. All time. /v1/analytics/foundational-skills/self-efficacy confidence",
    },
    {
      id: 'AAQ-231',
      tab: 'Highlights',
      subTab: 'Quality & sentiment',
      title: 'Confidence against competence',
      kind: 'chart',
      chartType: 'ScatterChart',
      componentFile: f('Analytics/PerceptionSection.tsx'),
      note: 'L9 calibration. x = self-rating (0–10), y = FHS level of the nearest scored cut (±30 days) where the skill was assessable; over-confident / calibrated / under-confident beyond ±0.75 levels after rescaling 1 + 3·r/10, one point per learner (latest) for shares and Spearman r; points withheld below minSampleSize. Over-confidence on harm is flagged INTERNAL (unaudited judge coding). /v1/analytics/foundational-skills/self-efficacy calibration',
    },
    {
      id: 'AAQ-232',
      tab: 'Highlights',
      subTab: 'Orgs',
      title: 'Org effectiveness scorecard',
      kind: 'chart',
      chartType: 'table',
      componentFile: f('Analytics/OrgEffectivenessCard.tsx'),
      note: 'Ruler R1 + R10. Per non-test org, all time, one pass: measurable learners, own start→now composite change ± CI, share improving beyond the platform noise band, unhelpful-behaviour change, course completion, self-harm follow-up (internal: share only privately with partners), 6-month median-composite sparkline. Rows with < 20 measurable learners show counts only. Sorted by measurable learners. First candidate to expose to tenant admins later, with the same floors. /v1/analytics/effectiveness/orgs',
    },
  ];

/** Total number of registered charts — handy for the guard test and the UI. */
export const ADMIN_ANALYTICS_CHART_COUNT =
  ADMIN_ANALYTICS_CHART_REGISTRY.length;
