const PERMISSIONS: Record<string, string> = {
  // === USER MANAGEMENT ===
  EDIT_USER: 'edit:user',
  VIEW_USER_WAITING_LIST: 'view:user:waiting-list',
  EDIT_USER_ROLE: 'edit:user:role',

  // === CHAT MANAGEMENT ===
  VIEW_CHAT: 'view:chat',
  EDIT_CHAT: 'edit:chat',
  VIEW_CHAT_COUNSELOR: 'view:chat:counselor',
  VIEW_CHAT_DETAILS: 'view:chat:details',
  CREATE_CHAT_NOTE: 'edit:chat:note',

  // === CALL MANAGEMENT ===
  VIEW_CALL_LOGS: 'view:call:logs',
  VIEW_CALL_LOGS_SUMMARY: 'view:call:logs-summary',
  EDIT_CALL_DETAILS: 'edit:call:details',
  EDIT_CALL_INFO: 'edit:call:info',

  // Call action permissions (role-specific)
  EDIT_CALL_START: 'edit:call:start',
  EDIT_CALL_ACCEPT: 'edit:call:accept',
  EDIT_CALL_END: 'edit:call:end',
  EDIT_CALL_CANCEL: 'edit:call:cancel',

  // === MESSAGE MANAGEMENT ===
  VIEW_MESSAGE: 'view:message',
  VIEW_MESSAGE_FEEDBACK: 'view:message:feedback',
  EDIT_MESSAGE_FEEDBACK: 'edit:message:feedback',

  // === SUMMARY MANAGEMENT ===
  VIEW_SUMMARY: 'view:summary',
  EDIT_SUMMARY: 'edit:summary',
  EXPORT_SUMMARY: 'export:summary',
  CREATE_SUMMARY_FEEDBACK: 'edit:summary:feedback',

  // === ANALYTICS ===
  CREATE_ANALYTICS_DASHBOARD: 'edit:analytics:dashboard',

  // === LEARNING MODULE ===
  EDIT_SCENARIO: 'edit:scenario',
  VIEW_SCENARIO_SESSION: 'view:scenario-session',
  EDIT_SCENARIO_SESSION: 'edit:scenario-session',
  VIEW_ADMIN_SCENARIO_SESSION: 'view:admin:scenario-session',
  VIEW_SCENARIO_SESSION_DETAILS: 'view:scenario-session:details',
  CREATE_SCENARIO_MAP_EVENTS: 'edit:scenario-session:map-events',
  VIEW_SESSION_SCENARIO_MESSAGES: 'view:session-scenario:messages',
  VIEW_SESSION_SCENARIO_SUMMARY: 'view:scenario-session:summary',

  // === SETTINGS ===
  VIEW_SETTINGS_SUMMARY_FIELDS: 'view:settings:summary-fields',
  EDIT_SETTINGS_SUMMARY_FIELDS: 'edit:settings:summary-fields',
  VIEW_SETTINGS_NUDGE_STATUS: 'view:settings:nudge-status',
  EDIT_SETTINGS_NUDGE_STATUS: 'edit:settings:nudge-status',
  VIEW_SETTINGS_CHAT_TYPES: 'view:settings:chat-types',
  EDIT_SETTINGS_CHAT_TYPES: 'edit:settings:chat-types',

  // === TENANT MANAGEMENT ===
  VIEW_TENANT: 'view:tenant',
  EDIT_TENANT: 'edit:tenant',

  // === REFERENCE DOCUMENTS ===
  VIEW_REFERENCE_DOCUMENT: 'view:reference-document',
  EDIT_REFERENCE_DOCUMENT: 'edit:reference-document',
  DELETE_REFERENCE_DOCUMENT: 'delete:reference-document',
  UPLOAD_REFERENCE_DOCUMENT: 'upload:reference-document',
  UPDATE_REFERENCE_DOCUMENT_ARCHIVE: 'edit:reference-document:archive',

  // === LIVEKIT ===
  VIEW_LIVEKIT: 'view:livekit',
  EDIT_LIVEKIT: 'edit:livekit',

  // === SESSION EVENTS ===
  EDIT_SESSION_EVENTS: 'edit:session-events',

  // === MISC ENTITIES ===
  VIEW_COUNSELOR: 'view:counselor',
  VIEW_TAGS: 'view:tags',
  CREATE_ENHANCEMENT: 'edit:enhancement',
  VIEW_CHAT_NUDGE: 'view:chat:nudge',
  CREATE_TAG_POSITIVITY_RATINGS: 'edit:tag-positivity-ratings',

  // === CLOUD TELEPHONY ===
  EDIT_CLOUD_TELEPHONY: 'edit:cloud-telephony',

  // === NAVIGATION PERMISSIONS ===
  VIEW_NAVBAR_CALLS: 'view:navbar:calls',
  VIEW_NAVBAR_CALENDAR: 'view:navbar:calendar',
  VIEW_NAVBAR_ANALYTICS: 'view:navbar:analytics',
  VIEW_NAVBAR_STRESS_BUSTER: 'view:navbar:stress-buster',
  VIEW_NAVBAR_SETTINGS: 'view:navbar:settings',
  VIEW_NAVBAR_SEARCH: 'view:navbar:search',
  VIEW_NAVBAR_COMMUNITY: 'view:navbar:community',
  VIEW_NAVBAR_LEARN: 'view:navbar:learn',

  // === BUTTON PERMISSIONS ===
  BUTTON_START_CALL: 'view:button:start-call',
};

const SUPER_ADMIN_PERMISSIONS = [
  // Full administrative access
  PERMISSIONS.EDIT_USER,
  PERMISSIONS.EDIT_USER_ROLE,
  PERMISSIONS.VIEW_CALL_LOGS,
  PERMISSIONS.EXPORT_SUMMARY,
  PERMISSIONS.EDIT_SCENARIO,
  PERMISSIONS.CREATE_SCENARIO_MAP_EVENTS,
  PERMISSIONS.VIEW_SETTINGS_SUMMARY_FIELDS,
  PERMISSIONS.EDIT_SETTINGS_SUMMARY_FIELDS,
  PERMISSIONS.EDIT_REFERENCE_DOCUMENT,
  PERMISSIONS.UPDATE_REFERENCE_DOCUMENT_ARCHIVE,
  PERMISSIONS.VIEW_TENANT,
  PERMISSIONS.EDIT_TENANT,
  PERMISSIONS.DELETE_REFERENCE_DOCUMENT,
  PERMISSIONS.UPLOAD_REFERENCE_DOCUMENT,
  PERMISSIONS.VIEW_LIVEKIT,
  PERMISSIONS.EDIT_LIVEKIT,
  PERMISSIONS.EDIT_SESSION_EVENTS,
  // Navigation
  PERMISSIONS.VIEW_NAVBAR_CALLS,
  PERMISSIONS.VIEW_NAVBAR_CALENDAR,
  PERMISSIONS.VIEW_NAVBAR_ANALYTICS,
  PERMISSIONS.VIEW_NAVBAR_STRESS_BUSTER,
  PERMISSIONS.VIEW_NAVBAR_SETTINGS,
  PERMISSIONS.VIEW_NAVBAR_SEARCH,
  PERMISSIONS.VIEW_NAVBAR_COMMUNITY,
  PERMISSIONS.VIEW_NAVBAR_LEARN,
  // Buttons
  PERMISSIONS.BUTTON_START_CALL,
];

const COUNSELOR_PERMISSIONS = [
  // Core counselor functions
  PERMISSIONS.VIEW_CHAT,
  PERMISSIONS.VIEW_USER_WAITING_LIST,
  PERMISSIONS.VIEW_CHAT_COUNSELOR,
  PERMISSIONS.VIEW_CHAT_DETAILS,
  PERMISSIONS.CREATE_CHAT_NOTE,
  PERMISSIONS.VIEW_CALL_LOGS,
  PERMISSIONS.EDIT_CALL_DETAILS,
  PERMISSIONS.EDIT_CALL_INFO,
  PERMISSIONS.EDIT_CALL_START,
  PERMISSIONS.EDIT_CALL_ACCEPT,
  PERMISSIONS.EDIT_CALL_END,
  PERMISSIONS.VIEW_REFERENCE_DOCUMENT,
  PERMISSIONS.VIEW_MESSAGE,
  PERMISSIONS.VIEW_MESSAGE_FEEDBACK,
  PERMISSIONS.EDIT_MESSAGE_FEEDBACK,
  PERMISSIONS.VIEW_SUMMARY,
  PERMISSIONS.EDIT_SUMMARY, // old
  PERMISSIONS.EXPORT_SUMMARY,
  PERMISSIONS.CREATE_SUMMARY_FEEDBACK,
  PERMISSIONS.VIEW_SETTINGS_SUMMARY_FIELDS,
  PERMISSIONS.EDIT_SETTINGS_SUMMARY_FIELDS,
  PERMISSIONS.VIEW_SETTINGS_NUDGE_STATUS,
  PERMISSIONS.EDIT_SETTINGS_NUDGE_STATUS,
  PERMISSIONS.VIEW_SETTINGS_CHAT_TYPES,
  PERMISSIONS.CREATE_ENHANCEMENT,
  PERMISSIONS.VIEW_CHAT_NUDGE,
  PERMISSIONS.CREATE_TAG_POSITIVITY_RATINGS,
  // Navigation
  PERMISSIONS.VIEW_NAVBAR_CALLS,
  PERMISSIONS.VIEW_NAVBAR_ANALYTICS,
  PERMISSIONS.VIEW_NAVBAR_SETTINGS,
  PERMISSIONS.VIEW_NAVBAR_LEARN,
  // Buttons
  PERMISSIONS.BUTTON_START_CALL,

  // Navbar
  PERMISSIONS.VIEW_NAVBAR_CALENDAR,
  PERMISSIONS.VIEW_NAVBAR_ANALYTICS,
  PERMISSIONS.VIEW_NAVBAR_LEARN,
  PERMISSIONS.VIEW_NAVBAR_STRESS_BUSTER,
  PERMISSIONS.VIEW_NAVBAR_SETTINGS,
];

const ADMIN_PERMISSIONS = [
  // Administrative access to core features
  PERMISSIONS.VIEW_CHAT_DETAILS,
  PERMISSIONS.CREATE_CHAT_NOTE,
  PERMISSIONS.VIEW_CALL_LOGS,
  PERMISSIONS.VIEW_CALL_LOGS_SUMMARY,
  PERMISSIONS.EDIT_CALL_DETAILS,
  PERMISSIONS.EDIT_CALL_INFO,
  PERMISSIONS.VIEW_MESSAGE,
  PERMISSIONS.EXPORT_SUMMARY,
  PERMISSIONS.CREATE_ANALYTICS_DASHBOARD,
  PERMISSIONS.VIEW_ADMIN_SCENARIO_SESSION,
  PERMISSIONS.VIEW_SCENARIO_SESSION_DETAILS,
  PERMISSIONS.VIEW_SESSION_SCENARIO_MESSAGES,
  PERMISSIONS.VIEW_SETTINGS_SUMMARY_FIELDS,
  PERMISSIONS.EDIT_SETTINGS_SUMMARY_FIELDS,
  PERMISSIONS.VIEW_SETTINGS_NUDGE_STATUS,
  PERMISSIONS.EDIT_SETTINGS_NUDGE_STATUS,
  PERMISSIONS.VIEW_SETTINGS_CHAT_TYPES,
  PERMISSIONS.EDIT_SETTINGS_CHAT_TYPES,
  PERMISSIONS.VIEW_COUNSELOR,
  PERMISSIONS.VIEW_TAGS,
  PERMISSIONS.CREATE_ENHANCEMENT,
  PERMISSIONS.CREATE_TAG_POSITIVITY_RATINGS,

];

const LEARNER_PERMISSIONS = [
  // Learning focused permissions
  PERMISSIONS.VIEW_SCENARIO_SESSION,
  PERMISSIONS.EDIT_SCENARIO_SESSION,
  PERMISSIONS.VIEW_SCENARIO_SESSION_DETAILS,
  PERMISSIONS.VIEW_SESSION_SCENARIO_MESSAGES,
  // Navigation
  PERMISSIONS.VIEW_NAVBAR_LEARN,
];

const CLIENT_PERMISSIONS = [
  // Basic client functions
  PERMISSIONS.VIEW_CHAT,
  PERMISSIONS.EDIT_CHAT, // Limited to own chats
  PERMISSIONS.EDIT_CALL_END, // Can end their own calls
  PERMISSIONS.EDIT_CALL_CANCEL, // Can cancel their own calls
  // Navigation
  PERMISSIONS.VIEW_NAVBAR_CALLS,
  // Buttons
  PERMISSIONS.BUTTON_START_CALL,
];

export {
  PERMISSIONS,
  SUPER_ADMIN_PERMISSIONS,
  COUNSELOR_PERMISSIONS,
  ADMIN_PERMISSIONS,
  LEARNER_PERMISSIONS,
  CLIENT_PERMISSIONS,
};
