const PERMISSIONS = {
  // === USER MANAGEMENT ===
  EDIT_USER: 'edit:user',
  EDIT_USER_ROLE: 'edit:user:role',
  VIEW_USERS: 'view:users',
  EDIT_USER_STATUS: 'edit:user:status',
  VIEW_USER_ROLES: 'view:user:roles',
  VIEW_USER_TENANT: 'view:user:tenant',

  // === CHAT MANAGEMENT ===
  VIEW_CHAT: 'view:chat',
  EDIT_CHAT: 'edit:chat',
  VIEW_CHAT_COUNSELOR: 'view:chat:counselor',
  VIEW_CHAT_DETAILS: 'view:chat:details',
  EDIT_CHAT_NOTE: 'edit:chat:note',
  DELETE_CHAT: 'delete:chat',

  // === CALL MANAGEMENT ===
  VIEW_CALL_LOGS: 'view:call:logs',
  VIEW_CALL_LOGS_SUMMARY: 'view:call:logs-summary',
  ARCHIVE_CALL_LOG: 'archive:call-log',
  EDIT_CALL_DETAILS: 'edit:call:details',
  EDIT_CALL_INFO: 'edit:call:info',

  // Call action permissions (role-specific)
  EDIT_CALL_END: 'edit:call:end',

  // === MESSAGE MANAGEMENT ===
  VIEW_MESSAGES: 'view:messages',
  VIEW_MESSAGE_FEEDBACK: 'view:message:feedback',
  EDIT_MESSAGE_FEEDBACK: 'edit:message:feedback',

  // === SUMMARY MANAGEMENT ===
  VIEW_SUMMARY: 'view:summary',
  EDIT_SUMMARY: 'edit:summary',
  EXPORT_SUMMARY: 'export:summary', // already present
  EDIT_SUMMARY_FEEDBACK: 'edit:summary:feedback',

  // === ANALYTICS ===
  EDIT_ANALYTICS_DASHBOARD: 'edit:analytics:dashboard',
  VIEW_ANALYTICS_DASHBOARD_URL: 'view:analytics:dashboard-url',
  VIEW_ANALYTICS_DASHBOARD: 'view:analytics:dashboard',

  // === LEARNING MODULE ===
  VIEW_SCENARIOS: 'view:scenarios',
  VIEW_SCENARIO: 'view:scenario',
  EDIT_SCENARIO: 'edit:scenario',
  VIEW_SCENARIO_SESSION: 'view:scenario-session',
  EDIT_SCENARIO_SESSION: 'edit:scenario-session',
  EDIT_SCENARIO_SESSION_FEEDBACK: 'edit:scenario-session:feedback',
  VIEW_ADMIN_SCENARIO_SESSION: 'view:admin:scenario-session',
  VIEW_SCENARIO_SESSION_DETAILS: 'view:scenario-session:details',
  VIEW_SCENARIO_EVENTS: 'view:scenario-events',
  EDIT_SCENARIO_MAP_EVENTS: 'edit:scenario-session:map-events',
  VIEW_SESSION_SCENARIO_MESSAGES: 'view:session-scenario:messages',
  VIEW_SESSION_SCENARIO_SUMMARY: 'view:scenario-session:summary',
  DELETE_SCENARIO_SESSION: 'delete:scenario-session',
  VIEW_SCENARIO_VOICES: 'view:scenario-voices',
  EDIT_SCENARIO_VOICE: 'edit:scenario-voice',
  VIEW_ADMIN_SCENARIOS: 'view:admin:scenarios',
  VIEW_ADMIN_SCENARIO: 'view:admin:scenario',
  DELETE_ADMIN_SCENARIO: 'delete:admin:scenario',
  EDIT_SCENARIO_TENANT: 'edit:scenario-tenant',
  DELETE_SCENARIO_TENANT: 'delete:scenario-tenant',
  VIEW_ADMIN_SCENARIO_VOICE_LANGUAGES: 'view:admin:scenario-voice-languages',
  EDIT_USER_PREFERENCES: 'edit:user:preferences',
  VIEW_USER_PREFERENCES: 'view:user:preferences',
  EDIT_LANGUAGE: 'edit:admin:language',
  VIEW_SCENARIO_LANGUAGES: 'view:scenario-languages',
  VIEW_ADMIN_LANGUAGES: 'view:admin:languages',

  // === SETTINGS ===
  VIEW_SETTINGS_SUMMARY_FIELDS: 'view:settings:summary-fields',
  EDIT_SETTINGS_SUMMARY_FIELDS: 'edit:settings:summary-fields',
  VIEW_SETTINGS_NUDGE_STATUS: 'view:settings:nudge-status',
  EDIT_SETTINGS_NUDGE_STATUS: 'edit:settings:nudge-status',
  VIEW_SETTINGS_CHAT_TYPES: 'view:settings:chat-types',
  EDIT_SETTINGS_CHAT_TYPES: 'edit:settings:chat-types',
  EDIT_GLOBAL_SETTINGS: 'edit:global-settings',

  // === TENANT MANAGEMENT ===
  VIEW_TENANT: 'view:tenant',
  EDIT_TENANT: 'edit:tenant',
  VIEW_TENANTS: 'view:tenants',

  // === REFERENCE DOCUMENTS ===
  VIEW_REFERENCE_DOCUMENT: 'view:reference-document',
  EDIT_REFERENCE_DOCUMENT: 'edit:reference-document',
  DELETE_REFERENCE_DOCUMENT: 'delete:reference-document',
  UPLOAD_REFERENCE_DOCUMENT: 'upload:reference-document',
  UPDATE_REFERENCE_DOCUMENT_ARCHIVE: 'edit:reference-document:archive',

  // === LIVEKIT ===
  VIEW_LIVEKIT: 'view:livekit',
  EDIT_LIVEKIT: 'edit:livekit',

  // === SESSION EVENTS ===
  EDIT_SESSION_EVENTS: 'edit:session-events',
  VIEW_SESSION_EVENTS: 'view:session-events',
  DELETE_SESSION_EVENTS: 'delete:session-events',

  VIEW_COUNSELORS: 'view:counselors',
  VIEW_TAGS: 'view:tags',
  EDIT_ENHANCEMENT: 'edit:enhancement',
  VIEW_CHAT_NUDGE: 'view:chat:nudge',
  EDIT_TAG_POSITIVITY_RATINGS: 'edit:tag-positivity-ratings',

  // === CLOUD TELEPHONY ===
  EDIT_CLOUD_TELEPHONY: 'edit:cloud-telephony',

  // UI Specific Permissions
  VIEW_ANALYTICS: 'view:analytics',
  VIEW_COMMUNITY: 'view:community',

  // === OZONETEL ===
  SUBSCRIBE_OZONETEL_EVENTS: 'subscribe:ozonetel:events',
  UNSUBSCRIBE_OZONETEL_EVENTS: 'unsubscribe:ozonetel:events',
  PROCESS_OZONETEL_WEBHOOK: 'process:ozonetel:webhook',

  // AUDIO UPLOAD
  VIEW_AUDIO_UPLOAD: 'view:audio-upload-url',
  CANCEL_AUDIO_UPLOAD: 'cancel:audio-upload',
  // === CONTEXT MANAGEMENT ===
  START_CLOUD_TELEPHONY_CHAT: 'start:cloud-telephony-chat',

  // === SYSTEM ACCESS ===
  SYSTEM_ACCESS: 'system:access',
  ORGANIZATION_ACCESS: 'organization:access',

  // === LEARNER ACCESS ===
  LEARNER_ACCESS: 'learner:access',

  // === COUNSELOR ACCESS ===
  COUNSELOR_ACCESS: 'counselor:access',

  // === AUDIO CHAT ===
  START_MICROPHONE_CHAT: 'start:microphone-chat',

  // === PLACES ===
  VIEW_PLACES: 'view:places',

  // === CHARACTER LIBRARY ===
  VIEW_SCENARIO_CHARACTER: 'view:scenario-character',
  EDIT_SCENARIO_CHARACTER: 'edit:scenario-character',
  DELETE_SCENARIO_CHARACTER: 'delete:scenario-character',
  CREATE_SCENARIO_CHARACTER: 'create:scenario-character',

  // === PROMPTS ===
  VIEW_PROMPT: 'view:admin:prompts',
  EDIT_PROMPT: 'edit:admin:prompts',

  VIEW_GUARDRAILS: 'view:admin:guardrails',
  EDIT_GUARDRAILS: 'edit:admin:guardrails',

  // === CACHE ===
  VIEW_CACHE: 'view:cache',
  DELETE_CACHE: 'delete:cache',

  //=== SIMULATION CREDITS ===
  VIEW_SIMULATION_CREDITS: 'view:simulation-credits',
  EDIT_SIMULATION_CREDITS: 'edit:simulation-credits',

  // === SCENARIO PATHS ===
  VIEW_ADMIN_SCENARIO_PATHS: 'view:admin:scenario-paths',
  VIEW_ADMIN_SCENARIO_PATH: 'view:admin:scenario-path',
  EDIT_ADMIN_SCENARIO_PATH: 'edit:admin:scenario-path',
  DELETE_ADMIN_SCENARIO_PATH: 'delete:admin:scenario-path',
  EDIT_TENANT_SCENARIO_PATH: 'edit:tenant:scenario-path',
  VIEW_SCENARIO_PATHS: 'view:scenario-paths',
  VIEW_SCENARIO_PATH: 'view:scenario-path',
  EDIT_SCENARIO_PATH: 'edit:scenario-path',
  EDIT_SCENARIO_PATH_TENANT: 'edit:scenario-path-tenant',
  DELETE_SCENARIO_PATH_TENANT: 'delete:scenario-path-tenant',

  // === CASES ===
  VIEW_ADMIN_CASES: 'view:admin:cases',
  VIEW_ADMIN_CASE: 'view:admin:case',
  EDIT_ADMIN_CASE: 'edit:admin:case',
  DELETE_ADMIN_CASE: 'delete:admin:case',
  EDIT_CASE_TENANT: 'edit:case-tenant',
  VIEW_CASES: 'view:cases',
  VIEW_CASE: 'view:case',
  EDIT_CASE: 'edit:case',
  DELETE_CASE_TENANT: 'delete:case-tenant',

  // === REVIEW ===
  // TODO: Remove these permissions later. Maintaining them for backward compatibility.
  VIEW_REVIEW: 'view:review',
  EDIT_REVIEW: 'edit:review',
  VIEW_REVIEWS: 'view:reviews',
  VIEW_REVIEW_THREADS: 'view:review-threads',
  EDIT_REVIEW_THREAD: 'edit:review-thread',
  REVIEWER_ACCESS: 'reviewer:access',

  // === SIMULATION REVIEW ===
  VIEW_SIMULATION_REVIEW: 'view:simulation-review',
  EDIT_SIMULATION_REVIEW: 'edit:simulation-review',
  VIEW_SIMULATION_REVIEWS: 'view:simulation-reviews',
  VIEW_SIMULATION_REVIEW_THREADS: 'view:simulation-review-threads',
  EDIT_SIMULATION_REVIEW_THREAD: 'edit:simulation-review-thread',
  SIMULATION_REVIEWER_ACCESS: 'simulation-reviewer:access',

  // === SCRIBE REVIEW ===
  VIEW_SCRIBE_REVIEW: 'view:scribe-review',
  EDIT_SCRIBE_REVIEW: 'edit:scribe-review',
  VIEW_SCRIBE_REVIEWS: 'view:scribe-reviews',
  VIEW_SCRIBE_REVIEW_THREADS: 'view:scribe-review-threads',
  EDIT_SCRIBE_REVIEW_THREAD: 'edit:scribe-review-thread',
  SCRIBE_REVIEWER_ACCESS: 'scribe-reviewer:access',

  // === BADGES ===
  VIEW_USER_BADGES: 'view:user:badges',
  EDIT_USER_BADGES: 'edit:user:badges',
  VIEW_ADMIN_BADGES: 'view:admin:badges',
  EDIT_ADMIN_BADGES: 'edit:admin:badges',

  // === COMMUNITY ===
  VIEW_COMMUNITY_LEADERBOARD: 'view:community:leaderboard',
  VIEW_USER_RANK: 'view:user:rank',

  // === COVER IMAGE LIBRARY ===
  VIEW_SCENARIO_COVER_IMAGE_LIBRARY: 'view:scenario-cover-image-library',
  EDIT_SCENARIO_COVER_IMAGE_LIBRARY: 'edit:scenario-cover-image-library',
  DELETE_SCENARIO_COVER_IMAGE_LIBRARY: 'delete:scenario-cover-image-library',
  // === SCENARIO REPORTS ===
  VIEW_SCENARIO_REPORTS: 'view:scenario-reports',
  EDIT_SCENARIO_REPORTS: 'edit:scenario-reports',

  // === MULTI-TENANT ADMIN MANAGEMENT ===
  VIEW_MULTI_TENANT_ADMINS: 'view:multi-tenant-admins',
  EDIT_MULTI_TENANT_ADMINS: 'edit:multi-tenant-admins',
};

const SUPER_ADMIN_PERMISSIONS = [
  // Full administrative access
  PERMISSIONS.SYSTEM_ACCESS,
  PERMISSIONS.EDIT_USER,
  PERMISSIONS.EDIT_USER_ROLE,
  PERMISSIONS.VIEW_USERS,
  PERMISSIONS.EDIT_USER_STATUS,
  PERMISSIONS.VIEW_USER_ROLES,
  PERMISSIONS.VIEW_CALL_LOGS,
  PERMISSIONS.EXPORT_SUMMARY,
  PERMISSIONS.EDIT_SCENARIO,
  PERMISSIONS.VIEW_SCENARIO_EVENTS,
  PERMISSIONS.EDIT_SCENARIO_MAP_EVENTS,
  PERMISSIONS.VIEW_SETTINGS_SUMMARY_FIELDS,
  PERMISSIONS.EDIT_SETTINGS_SUMMARY_FIELDS,
  PERMISSIONS.EDIT_REFERENCE_DOCUMENT,
  PERMISSIONS.UPDATE_REFERENCE_DOCUMENT_ARCHIVE,
  PERMISSIONS.VIEW_TENANT,
  PERMISSIONS.EDIT_TENANT,
  PERMISSIONS.VIEW_TENANTS,
  PERMISSIONS.DELETE_REFERENCE_DOCUMENT,
  PERMISSIONS.UPLOAD_REFERENCE_DOCUMENT,
  PERMISSIONS.VIEW_LIVEKIT,
  PERMISSIONS.EDIT_LIVEKIT,
  PERMISSIONS.EDIT_SESSION_EVENTS,
  PERMISSIONS.VIEW_SETTINGS_CHAT_TYPES,
  PERMISSIONS.EDIT_SETTINGS_CHAT_TYPES,
  PERMISSIONS.EDIT_CLOUD_TELEPHONY,
  PERMISSIONS.SUBSCRIBE_OZONETEL_EVENTS,
  PERMISSIONS.UNSUBSCRIBE_OZONETEL_EVENTS,
  PERMISSIONS.DELETE_SCENARIO_SESSION,
  PERMISSIONS.VIEW_CACHE,
  PERMISSIONS.DELETE_CACHE,
  PERMISSIONS.VIEW_SESSION_EVENTS,
  PERMISSIONS.VIEW_SCENARIO_VOICES,
  PERMISSIONS.EDIT_SCENARIO_VOICE,
  PERMISSIONS.VIEW_SIMULATION_CREDITS,
  PERMISSIONS.EDIT_SIMULATION_CREDITS,
  PERMISSIONS.DELETE_SESSION_EVENTS,
  PERMISSIONS.VIEW_ADMIN_SCENARIOS,
  PERMISSIONS.VIEW_ADMIN_SCENARIO,
  PERMISSIONS.DELETE_ADMIN_SCENARIO,
  PERMISSIONS.EDIT_ANALYTICS_DASHBOARD,
  PERMISSIONS.VIEW_ADMIN_SCENARIO_PATHS,
  PERMISSIONS.VIEW_ADMIN_SCENARIO_PATH,
  PERMISSIONS.EDIT_ADMIN_SCENARIO_PATH,
  PERMISSIONS.DELETE_ADMIN_SCENARIO_PATH,
  PERMISSIONS.EDIT_TENANT_SCENARIO_PATH,
  PERMISSIONS.EDIT_SCENARIO_PATH_TENANT,
  PERMISSIONS.DELETE_SCENARIO_PATH_TENANT,
  PERMISSIONS.EDIT_SCENARIO_TENANT,
  PERMISSIONS.DELETE_SCENARIO_TENANT,
  PERMISSIONS.VIEW_ADMIN_SCENARIO_VOICE_LANGUAGES,
  PERMISSIONS.EDIT_LANGUAGE,
  PERMISSIONS.VIEW_SCENARIO_LANGUAGES,
  PERMISSIONS.VIEW_ADMIN_LANGUAGES,
  PERMISSIONS.VIEW_ADMIN_BADGES,
  PERMISSIONS.EDIT_ADMIN_BADGES,
  PERMISSIONS.VIEW_SCENARIO_CHARACTER,
  PERMISSIONS.EDIT_SCENARIO_CHARACTER,
  PERMISSIONS.DELETE_SCENARIO_CHARACTER,
  PERMISSIONS.CREATE_SCENARIO_CHARACTER,
  PERMISSIONS.VIEW_PROMPT,
  PERMISSIONS.EDIT_PROMPT,
  PERMISSIONS.VIEW_GUARDRAILS,
  PERMISSIONS.EDIT_GUARDRAILS,
  PERMISSIONS.VIEW_SCENARIO_COVER_IMAGE_LIBRARY,
  PERMISSIONS.EDIT_SCENARIO_COVER_IMAGE_LIBRARY,
  PERMISSIONS.DELETE_SCENARIO_COVER_IMAGE_LIBRARY,
  PERMISSIONS.VIEW_SCENARIO_REPORTS,
  PERMISSIONS.EDIT_SCENARIO_REPORTS,
  PERMISSIONS.EDIT_GLOBAL_SETTINGS,
  PERMISSIONS.VIEW_MULTI_TENANT_ADMINS,
  PERMISSIONS.EDIT_MULTI_TENANT_ADMINS,
];

const COUNSELOR_PERMISSIONS = [
  // Core counselor functions
  PERMISSIONS.VIEW_CHAT,
  PERMISSIONS.VIEW_CHAT_COUNSELOR,
  PERMISSIONS.VIEW_CHAT_DETAILS,
  PERMISSIONS.EDIT_CHAT_NOTE,
  PERMISSIONS.VIEW_CALL_LOGS,
  PERMISSIONS.EDIT_CALL_DETAILS,
  PERMISSIONS.EDIT_CALL_INFO,
  PERMISSIONS.EDIT_CALL_END,
  PERMISSIONS.ARCHIVE_CALL_LOG,
  PERMISSIONS.VIEW_REFERENCE_DOCUMENT,
  PERMISSIONS.VIEW_MESSAGES,
  PERMISSIONS.VIEW_MESSAGE_FEEDBACK,
  PERMISSIONS.EDIT_MESSAGE_FEEDBACK,
  PERMISSIONS.VIEW_SUMMARY,
  PERMISSIONS.EDIT_SUMMARY, // old
  PERMISSIONS.EXPORT_SUMMARY,
  PERMISSIONS.EDIT_SUMMARY_FEEDBACK,
  PERMISSIONS.VIEW_SETTINGS_SUMMARY_FIELDS,
  PERMISSIONS.VIEW_SETTINGS_NUDGE_STATUS,
  PERMISSIONS.EDIT_SETTINGS_NUDGE_STATUS,
  PERMISSIONS.VIEW_SETTINGS_CHAT_TYPES,
  PERMISSIONS.EDIT_ENHANCEMENT,
  PERMISSIONS.VIEW_CHAT_NUDGE,
  PERMISSIONS.EDIT_TAG_POSITIVITY_RATINGS,

  PERMISSIONS.VIEW_ANALYTICS,
  PERMISSIONS.VIEW_COMMUNITY,

  PERMISSIONS.START_CLOUD_TELEPHONY_CHAT,
  PERMISSIONS.START_MICROPHONE_CHAT,
  PERMISSIONS.VIEW_ANALYTICS_DASHBOARD_URL,
  PERMISSIONS.VIEW_ANALYTICS_DASHBOARD,
  PERMISSIONS.PROCESS_OZONETEL_WEBHOOK,
  PERMISSIONS.VIEW_PLACES,
  PERMISSIONS.VIEW_USER_TENANT,

  PERMISSIONS.VIEW_SCRIBE_REVIEW,
  PERMISSIONS.EDIT_SCRIBE_REVIEW,
  PERMISSIONS.VIEW_SCRIBE_REVIEW_THREADS,
  PERMISSIONS.EDIT_SCRIBE_REVIEW_THREAD,
  PERMISSIONS.COUNSELOR_ACCESS,
];

const ADMIN_PERMISSIONS = [
  // Administrative access to core features
  PERMISSIONS.ORGANIZATION_ACCESS,
  PERMISSIONS.VIEW_CHAT_DETAILS,
  PERMISSIONS.VIEW_CALL_LOGS_SUMMARY,
  PERMISSIONS.VIEW_MESSAGES,
  PERMISSIONS.EXPORT_SUMMARY,
  PERMISSIONS.VIEW_ADMIN_SCENARIO_SESSION,
  PERMISSIONS.VIEW_SCENARIO_SESSION_DETAILS,
  PERMISSIONS.VIEW_SESSION_SCENARIO_MESSAGES,
  PERMISSIONS.VIEW_SETTINGS_SUMMARY_FIELDS,
  PERMISSIONS.VIEW_SETTINGS_NUDGE_STATUS,
  PERMISSIONS.EDIT_SETTINGS_NUDGE_STATUS,
  PERMISSIONS.VIEW_SETTINGS_CHAT_TYPES,
  PERMISSIONS.VIEW_COUNSELORS,
  PERMISSIONS.VIEW_TAGS,
  PERMISSIONS.EDIT_TAG_POSITIVITY_RATINGS,

  PERMISSIONS.VIEW_ANALYTICS,
  PERMISSIONS.VIEW_COMMUNITY,
  PERMISSIONS.VIEW_AUDIO_UPLOAD,
  PERMISSIONS.CANCEL_AUDIO_UPLOAD,
  PERMISSIONS.DELETE_CHAT,
  PERMISSIONS.EDIT_REFERENCE_DOCUMENT,
  PERMISSIONS.VIEW_ANALYTICS_DASHBOARD_URL,
  PERMISSIONS.VIEW_ANALYTICS_DASHBOARD,

  PERMISSIONS.VIEW_USER_TENANT,

  PERMISSIONS.VIEW_SCRIBE_REVIEW,
  PERMISSIONS.EDIT_SCRIBE_REVIEW,
  PERMISSIONS.VIEW_SCRIBE_REVIEW_THREADS,
  PERMISSIONS.EDIT_SCRIBE_REVIEW_THREAD,
];

const MULTI_TENANT_ADMIN_PERMISSIONS = [
  PERMISSIONS.EDIT_SCENARIO,
  PERMISSIONS.VIEW_ADMIN_SCENARIO,
  PERMISSIONS.VIEW_ADMIN_SCENARIOS,
  PERMISSIONS.VIEW_SCENARIO_LANGUAGES,
  PERMISSIONS.VIEW_SCENARIO_CHARACTER,
  PERMISSIONS.VIEW_ADMIN_SCENARIO_VOICE_LANGUAGES,
];

const LEARNER_PERMISSIONS = [
  // Learning focused permissions
  PERMISSIONS.VIEW_SCENARIOS,
  PERMISSIONS.VIEW_SCENARIO,
  PERMISSIONS.VIEW_SCENARIO_SESSION,
  PERMISSIONS.EDIT_SCENARIO_SESSION,
  PERMISSIONS.EDIT_SCENARIO_SESSION_FEEDBACK,
  PERMISSIONS.VIEW_SCENARIO_SESSION_DETAILS,
  PERMISSIONS.VIEW_SESSION_SCENARIO_MESSAGES,

  PERMISSIONS.VIEW_ANALYTICS,
  PERMISSIONS.VIEW_ANALYTICS_DASHBOARD,
  PERMISSIONS.VIEW_ANALYTICS_DASHBOARD_URL,
  PERMISSIONS.VIEW_SIMULATION_CREDITS,
  PERMISSIONS.VIEW_SCENARIO_PATHS,
  PERMISSIONS.VIEW_SCENARIO_PATH,
  PERMISSIONS.EDIT_SCENARIO_PATH,

  PERMISSIONS.EDIT_USER_PREFERENCES,
  PERMISSIONS.VIEW_USER_PREFERENCES,
  PERMISSIONS.VIEW_SCENARIO_LANGUAGES,

  PERMISSIONS.VIEW_USER_TENANT,

  // OLD LEARNER PERMISSIONS
  // TODO: Remove these permissions (VIEW_REVIEW, EDIT_REVIEW, VIEW_REVIEW_THREADS, EDIT_REVIEW_THREAD) later.
  // Maintaining them for backward compatibility.
  PERMISSIONS.VIEW_REVIEW,
  PERMISSIONS.EDIT_REVIEW,
  PERMISSIONS.VIEW_REVIEW_THREADS,
  PERMISSIONS.EDIT_REVIEW_THREAD,

  PERMISSIONS.VIEW_SIMULATION_REVIEW,
  PERMISSIONS.EDIT_SIMULATION_REVIEW,
  PERMISSIONS.VIEW_SIMULATION_REVIEW_THREADS,
  PERMISSIONS.EDIT_SIMULATION_REVIEW_THREAD,
  PERMISSIONS.LEARNER_ACCESS,
  PERMISSIONS.VIEW_USER_BADGES,
  PERMISSIONS.EDIT_USER_BADGES,

  PERMISSIONS.VIEW_COMMUNITY_LEADERBOARD,
  PERMISSIONS.VIEW_USER_RANK,
];

const CLIENT_PERMISSIONS = [
  PERMISSIONS.VIEW_CHAT,
  PERMISSIONS.EDIT_CHAT,
  PERMISSIONS.EDIT_CALL_END,
];

const SIMULATION_REVIEWER_PERMISSIONS = [
  // OLD SIMULATION REVIEWER PERMISSIONS
  // TODO: Remove these permissions (VIEW_REVIEW, VIEW_REVIEWS, VIEW_REVIEW_THREADS, EDIT_REVIEW_THREAD, REVIEWER_ACCESS) later.
  // Maintaining them for backward compatibility.
  PERMISSIONS.VIEW_REVIEW,
  PERMISSIONS.VIEW_REVIEWS,
  PERMISSIONS.VIEW_REVIEW_THREADS,
  PERMISSIONS.EDIT_REVIEW_THREAD,
  PERMISSIONS.REVIEWER_ACCESS,

  PERMISSIONS.VIEW_USER_TENANT,
  PERMISSIONS.VIEW_SIMULATION_REVIEW,
  PERMISSIONS.VIEW_SIMULATION_REVIEWS,
  PERMISSIONS.VIEW_SIMULATION_REVIEW_THREADS,
  PERMISSIONS.EDIT_SIMULATION_REVIEW_THREAD,
  PERMISSIONS.SIMULATION_REVIEWER_ACCESS,
  PERMISSIONS.VIEW_USER_BADGES,
  PERMISSIONS.EDIT_USER_BADGES,
];

const SCRIBE_REVIEWER_PERMISSIONS = [
  PERMISSIONS.VIEW_USER_TENANT,
  PERMISSIONS.VIEW_SCRIBE_REVIEW,
  PERMISSIONS.VIEW_SCRIBE_REVIEWS,
  PERMISSIONS.VIEW_SCRIBE_REVIEW_THREADS,
  PERMISSIONS.EDIT_SCRIBE_REVIEW_THREAD,
  PERMISSIONS.SCRIBE_REVIEWER_ACCESS,
];

export {
  PERMISSIONS,
  SUPER_ADMIN_PERMISSIONS,
  COUNSELOR_PERMISSIONS,
  ADMIN_PERMISSIONS,
  MULTI_TENANT_ADMIN_PERMISSIONS,
  LEARNER_PERMISSIONS,
  CLIENT_PERMISSIONS,
  SIMULATION_REVIEWER_PERMISSIONS,
  SCRIBE_REVIEWER_PERMISSIONS,
};
